Repository zen-mod/ZEN, pull requests merged in 2019-10, with the labels that each got.

#181 Fix VA incorrectly changing Zeus camera position
  addons/common/XEH_postInit.sqf
Labels: feature

#179 Add fixed altitude option to Ambient FlyBy
  addons/modules/RscAttributes.hpp
  addons/modules/functions/fnc_gui_ambientFlyby.sqf
  addons/modules/functions/fnc_moduleAmbientFlyby.sqf
  addons/modules/script_component.hpp
  addons/modules/stringtable.xml
Labels: enhancement

#187 Remove unused postInit from context_actions
  addons/context_actions/CfgEventHandlers.hpp
  addons/context_actions/XEH_postInit.sqf
Labels: cleanup, ignore changelog

#188 Optimize area marker icon update events
  addons/area_markers/XEH_PREP.hpp
  addons/area_markers/XEH_postInit.sqf
  addons/area_markers/functions/fnc_applyProperties.sqf
  addons/area_markers/functions/fnc_createIcon.sqf
  addons/area_markers/functions/fnc_onDraw.sqf
  addons/area_markers/functions/fnc_onKeyDown.sqf
  addons/area_markers/functions/fnc_setIconAngle.sqf
  addons/area_markers/functions/fnc_updateIcon.sqf
Labels: optimization

#195 Improve isPlacementActive common function
  addons/common/functions/fnc_isPlacementActive.sqf
Labels: cleanup

#183 Move garage GETDLC macro to common function
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_getDLC.sqf
  addons/common/functions/fnc_getSideIcon.sqf
  addons/garage/functions/fnc_showVehicleInfo.sqf
  addons/garage/script_component.hpp
Labels: cleanup

#200 Add custom waypoints framework documentation
  docs/_sidebar.md
  docs/custom_waypoints.md
Labels: documentation

#197 Fix include crew toggle to work with the recent tree
  addons/editor/functions/fnc_handleObjectPlaced.sqf
  addons/editor/functions/fnc_initDisplayCurator.sqf
Labels: bug fix

#194 Allow toggling garage interface using mouse buttons
  addons/garage/XEH_PREP.hpp
  addons/garage/functions/fnc_onMouseButtonClick.sqf
  addons/garage/gui.hpp
Labels: enhancement

#203 Fix ambient flyby selection saving
  addons/modules/functions/fnc_gui_ambientFlyby.sqf
  addons/modules/script_component.hpp
Labels: bug fix, ignore changelog

#204 Adjusted wording for attribute strings
  addons/attributes/stringtable.xml
Labels: ignore changelog, translation

#205 Improve ambient animation handling of dead units
  addons/modules/functions/fnc_moduleAmbientAnimEnd.sqf
Labels: enhancement

#191 Add translations CI workflow
  .github/workflows/translations.yml
  tools/deploy.py
  tools/stringtablediag.py
Labels: ignore changelog, tools

#184 Add selection saving to Side Relations dialog
  addons/modules/functions/fnc_gui_sideRelations.sqf
  addons/modules/functions/fnc_moduleSideRelations.sqf
Labels: enhancement

#192 Add coding guidelines documentation
  docs/_sidebar.md
  docs/coding_guidelines.md
  docs/index.html
Labels: documentation

#208 Add missing modules documentation
  addons/modules/stringtable.xml
  docs/modules_list.md
Labels: documentation

#193 Add garage button to apply customization to all selected vehicles
  addons/context_actions/CfgContext.hpp
  addons/garage/XEH_PREP.hpp
  addons/garage/functions/fnc_applyToAll.sqf
  addons/garage/gui.hpp
  addons/garage/stringtable.xml
Labels: enhancement

#199 Add fastrope waypoint
  addons/ai/functions/fnc_waypointFastrope.sqf
  addons/ai/stringtable.xml
  addons/attributes/CfgWaypointTypes.hpp
Labels: feature

#94 Add Create/Edit Intel module
  addons/common/XEH_postInit.sqf
  addons/main/script_mod.hpp
  addons/modules/CfgVehicles.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/XEH_postInit.sqf
  addons/modules/config.cpp
  addons/modules/functions/fnc_addIntelAction.sqf
  addons/modules/functions/fnc_moduleCreateIntel.sqf
  addons/modules/stringtable.xml
  docs/modules_list.md
Labels: feature

#185 Update German translations
  addons/ai/stringtable.xml
  addons/area_markers/stringtable.xml
  addons/attributes/stringtable.xml
  addons/camera/stringtable.xml
  addons/common/stringtable.xml
  addons/context_actions/stringtable.xml
  addons/editor/stringtable.xml
  addons/modules/stringtable.xml
  addons/visibility/stringtable.xml
  extras/blank/stringtable.xml
Labels: translation

#210 Various improvements to documentation
  README.md
  docs/_sidebar.md
  docs/assets/styles.css
  docs/development/coding_guidelines.md
  docs/frameworks/context_menu.md
  docs/frameworks/custom_modules.md
  docs/frameworks/custom_waypoints.md
  docs/frameworks/dynamic_dialog.md
  docs/frameworks/public_events.md
  docs/home.md
  docs/index.html
  docs/user_guide/area_markers.md
  docs/user_guide/attributes.md
  docs/user_guide/context_actions.md
  docs/user_guide/modules_list.md
Labels: documentation

#215 Improve Attach To module detaching
  addons/modules/functions/fnc_moduleAttachTo.sqf
Labels: enhancement

#218 Disable Apply To All button when no other vehicles are selected
  addons/garage/functions/fnc_openGarage.sqf
  addons/garage/gui.hpp
  addons/garage/script_component.hpp
  addons/garage/stringtable.xml
Labels: enhancement

#223 Update core team authors
  AUTHORS.txt
Labels: ignore changelog

#224 Remove unused _logic variable from module dialog functions
  addons/modules/functions/fnc_gui_editableObjects.sqf
  addons/modules/functions/fnc_gui_globalHint.sqf
  addons/modules/functions/fnc_gui_setDate.sqf
Labels: cleanup, ignore changelog

#228 Add portrait entry for CAS modules
  addons/modules/CfgVehicles.hpp
Labels: enhancement

#229 Fix healUnit function for ace_medical changes
  addons/common/XEH_preInit.sqf
  addons/common/functions/fnc_healUnit.sqf
Labels: bug fix

#230 Add 404 page to documentation
  docs/_404.md
  docs/assets/styles.css
  docs/index.html
Labels: documentation
