Repository zen-mod/ZEN, pull requests merged in 2019-12, with the labels that each got.

#266 Add SQF Validator
  azure-pipelines.yml
  tools/sqf_validator.py
Labels: ignore changelog, tools

#156 Damage Components Attribute
  addons/attributes/RscAttributes.hpp
  addons/attributes/XEH_PREP.hpp
  addons/attributes/XEH_postInit.sqf
  addons/attributes/functions/fnc_buttonComponents.sqf
  addons/attributes/stringtable.xml
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_getHitPointString.sqf
  addons/common/stringtable.xml
Labels: feature

#269 Improve inventory copy/paste context menu actions
  addons/context_actions/CfgContext.hpp
Labels: enhancement

#268 Add clear unit list button to Spawn Reinforcements module
  addons/modules/RscAttributes.hpp
  addons/modules/functions/fnc_gui_spawnReinforcements.sqf
  addons/modules/script_component.hpp
Labels: enhancement

#267 Add fly height option to Spawn Reinforcements module
  addons/common/functions/fnc_ejectPassengers.sqf
  addons/modules/RscAttributes.hpp
  addons/modules/functions/fnc_gui_spawnReinforcements.sqf
  addons/modules/functions/fnc_moduleSpawnReinforcements.sqf
  addons/modules/script_component.hpp
Labels: enhancement

#271 Fix editor preview hiding for items with no preview image
  addons/editor_previews/functions/fnc_handleMouseUpdate.sqf
Labels: bug fix
