Repository zen-mod/ZEN, pull requests merged in 2019-07, with the labels that each got.

#34 Improve context menu handling of active placement
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_getActiveTree.sqf
  addons/common/functions/fnc_isPlacementActive.sqf
  addons/common/script_component.hpp
  addons/context_menu/functions/fnc_initDisplayCurator.sqf
  addons/context_menu/initKeybinds.sqf
  addons/editor/RscDisplayCurator.hpp
  addons/editor/functions/fnc_handleTreeButtons.sqf
Labels: enhancement

#41 Full Polish Translation
  addons/ai/stringtable.xml
  addons/attributes/stringtable.xml
  addons/common/stringtable.xml
  addons/context_actions/stringtable.xml
  addons/context_menu/stringtable.xml
  addons/custom_modules/stringtable.xml
  addons/doors/stringtable.xml
  addons/editor/stringtable.xml
  addons/garage/stringtable.xml
  addons/main/stringtable.xml
  addons/modules/stringtable.xml
  addons/vision/stringtable.xml
Labels: translation

#44 Add settings to control camera properties
  addons/camera/$PBOPREFIX$
  addons/camera/CfgEventHandlers.hpp
  addons/camera/XEH_PREP.hpp
  addons/camera/XEH_postInit.sqf
  addons/camera/XEH_preInit.sqf
  addons/camera/XEH_preStart.sqf
  addons/camera/config.cpp
  addons/camera/functions/fnc_updateSettings.sqf
  addons/camera/functions/script_component.hpp
  addons/camera/initSettings.sqf
  addons/camera/script_component.hpp
  addons/camera/stringtable.xml
  addons/editor/XEH_preInit.sqf
  addons/editor/functions/fnc_initDisplayCurator.sqf
Labels: feature

#25 Improve object attachment hints
  addons/modules/functions/fnc_gui_fireMission.sqf
  addons/modules/functions/fnc_moduleAmbientAnim.sqf
  addons/modules/functions/fnc_moduleArsenal.sqf
  addons/modules/functions/fnc_moduleAssignZeus.sqf
  addons/modules/functions/fnc_moduleAttachFlag.sqf
  addons/modules/functions/fnc_moduleAttachTo.sqf
  addons/modules/functions/fnc_moduleBindVariable.sqf
  addons/modules/functions/fnc_moduleChangeHeight.sqf
  addons/modules/functions/fnc_moduleConvoyParameters.sqf
  addons/modules/functions/fnc_moduleCreateIED.sqf
  addons/modules/functions/fnc_moduleEquipWithECM.sqf
  addons/modules/functions/fnc_moduleFlyHeight.sqf
  addons/modules/functions/fnc_moduleGarrison.sqf
  addons/modules/functions/fnc_moduleGroupSide.sqf
  addons/modules/functions/fnc_moduleHeal.sqf
  addons/modules/functions/fnc_moduleMakeInvincible.sqf
  addons/modules/functions/fnc_modulePatrolArea.sqf
  addons/modules/functions/fnc_moduleSimulation.sqf
  addons/modules/functions/fnc_moduleSitOnChair.sqf
  addons/modules/functions/fnc_moduleSuicideBomber.sqf
  addons/modules/functions/fnc_moduleTurretOptics.sqf
  addons/modules/functions/fnc_moduleUnGarrison.sqf
  addons/modules/functions/fnc_moduleVisibility.sqf
  addons/modules/stringtable.xml
Labels: enhancement

#50 Change all links to new repository
  README.md
  addons/main/stringtable.xml
  mod.cpp
Labels: bug fix

#42 Add skills button to attributes displays
  addons/attributes/CfgEventHandlers.hpp
  addons/attributes/RscAttributes.hpp
  addons/attributes/XEH_PREP.hpp
  addons/attributes/XEH_postInit.sqf
  addons/attributes/config.cpp
  addons/attributes/functions/fnc_buttonSkills.sqf
  addons/attributes/functions/fnc_initAttributesDisplay.sqf
  addons/attributes/stringtable.xml
  addons/dialog/functions/fnc_create.sqf
  addons/dialog/functions/fnc_gui_slider.sqf
  addons/dialog/gui.hpp
  addons/garage/RscAttributes.hpp
  addons/inventory/RscAttributes.hpp
  docs/dynamic_dialog.md
Labels: feature

#56 Add multi-line edit box control types
  addons/dialog/functions/fnc_create.sqf
  addons/dialog/functions/fnc_gui_edit.sqf
  addons/dialog/gui.hpp
  docs/dynamic_dialog.md
Labels: feature

#59 Keep context menu open if clicked action does nothing
  addons/context_menu/functions/fnc_createContextGroup.sqf
Labels: enhancement

#51 Added Azure Pipelines support for CI builds
  .editorconfig
  .gitignore
  AUTHORS.txt
  Makefile
  VERSION
  addons/common/defineResinclDesign.inc
  azure-pipelines.yml
  include/x/cba/addons/main/script_macros_common.hpp
  mod.cpp
  tools/getArmake.ps1
Labels: bug fix, ignore changelog, tools

#58 Add performance counters
  addons/ai/script_component.hpp
  addons/attributes/script_component.hpp
  addons/camera/script_component.hpp
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_dumpPerformanceCounters.sqf
  addons/common/script_component.hpp
  addons/context_actions/script_component.hpp
  addons/context_menu/script_component.hpp
  addons/custom_modules/script_component.hpp
  addons/dialog/script_component.hpp
  addons/doors/script_component.hpp
  addons/editor/script_component.hpp
  addons/garage/script_component.hpp
  addons/inventory/script_component.hpp
  addons/main/script_component.hpp
  addons/main/script_debug.hpp
  addons/main/script_macros.hpp
  addons/modules/script_component.hpp
  addons/remote_control/script_component.hpp
  addons/vision/script_component.hpp
Labels: ignore changelog, tools

#46 Fix attach flag dropdown list
  addons/dialog/XEH_PREP.hpp
  addons/dialog/functions/fnc_create.sqf
  addons/dialog/functions/fnc_gui_list.sqf
  addons/dialog/gui.hpp
  addons/dialog/script_idc.hpp
  addons/modules/functions/fnc_moduleAttachFlag.sqf
  addons/modules/ui/flag_none_ca.paa
  docs/dynamic_dialog.md
Labels: bug fix, enhancement

#52 Add healing context action
  AUTHORS.txt
  addons/common/XEH_PREP.hpp
  addons/common/XEH_preInit.sqf
  addons/common/functions/fnc_healUnit.sqf
  addons/context_actions/CfgContext.hpp
  addons/context_actions/XEH_PREP.hpp
  addons/context_actions/functions/fnc_healUnits.sqf
  addons/context_actions/script_component.hpp
  addons/context_actions/ui/medical_cross_ca.paa
  addons/modules/functions/fnc_moduleHeal.sqf
Labels: feature

#68 Add periods to setting descriptions
  addons/common/stringtable.xml
  addons/context_menu/stringtable.xml
  addons/editor/stringtable.xml
Labels: cleanup

#65 Rotation of garrisoned units
  addons/ai/XEH_preInit.sqf
  addons/ai/functions/fnc_unGarrison.sqf
  addons/common/XEH_postInit.sqf
Labels: bug fix

#14 First version of Russian translation
  addons/attributes/stringtable.xml
  addons/common/stringtable.xml
  addons/context_actions/stringtable.xml
  addons/context_menu/stringtable.xml
  addons/custom_modules/stringtable.xml
  addons/doors/stringtable.xml
  addons/editor/stringtable.xml
  addons/garage/stringtable.xml
  addons/modules/stringtable.xml
  addons/vision/stringtable.xml
Labels: translation

#35 Fix cycle waypoint position
  addons/editor/functions/fnc_bi_curatorWaypointPlaced.sqf
Labels: bug fix

#36 Fix copy/pasted modules
  addons/modules/XEH_preInit.sqf
Labels: bug fix

#71 Fix README image on mobile
  README.md
Labels: ignore changelog

#70 Add sensors button to attributes displays
  addons/attributes/RscAttributes.hpp
  addons/attributes/XEH_PREP.hpp
  addons/attributes/XEH_postInit.sqf
  addons/attributes/functions/fnc_buttonSensors.sqf
  addons/attributes/functions/fnc_buttonSkills.sqf
  addons/attributes/stringtable.xml
Labels: feature

#73 Extend set date module year range
  addons/modules/functions/fnc_gui_setDate.sqf
Labels: enhancement

#77 Offset context menu opening position
  addons/context_menu/functions/fnc_createContextGroup.sqf
Labels: enhancement

#76 Change fire mission default mode to target module
  addons/modules/functions/fnc_gui_fireMission.sqf
Labels: enhancement

#75 Show custom modules in recent tree
  addons/custom_modules/CfgFactionClasses.hpp
  addons/custom_modules/CfgVehicles.hpp
  addons/custom_modules/config.cpp
  addons/custom_modules/functions/fnc_addModules.sqf
Labels: enhancement

#81 Add group side button to attributes display
  addons/attributes/RscAttributes.hpp
  addons/attributes/XEH_PREP.hpp
  addons/attributes/functions/fnc_buttonSide.sqf
  addons/attributes/stringtable.xml
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_changeGroupSide.sqf
  addons/modules/functions/fnc_moduleGroupSide.sqf
Labels: feature

#82 Disable attributes for JIP execute code module
  addons/attributes/functions/fnc_bi_showCuratorAttributes.sqf
  addons/modules/functions/fnc_gui_cas.sqf
  addons/modules/functions/fnc_gui_executeCode.sqf
Labels: bug fix

#57 Add vehicle logistics context actions
  addons/context_actions/CfgContext.hpp
  addons/context_actions/XEH_PREP.hpp
  addons/context_actions/functions/fnc_rearmVehicles.sqf
  addons/context_actions/functions/fnc_refuelVehicles.sqf
  addons/context_actions/functions/fnc_repairVehicles.sqf
  addons/context_actions/stringtable.xml
Labels: feature

#79 Add change weather module
  addons/dialog/functions/fnc_create.sqf
  addons/dialog/functions/fnc_gui_slider.sqf
  addons/modules/CfgVehicles.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/XEH_postInit.sqf
  addons/modules/config.cpp
  addons/modules/functions/fnc_moduleWeather.sqf
  addons/modules/script_component.hpp
  addons/modules/stringtable.xml
  docs/dynamic_dialog.md
Labels: feature

#80 Improve dialog toolbox control
  addons/dialog/functions/fnc_create.sqf
  addons/dialog/functions/fnc_gui_toolbox.sqf
  addons/dialog/gui.hpp
  addons/modules/functions/fnc_moduleCreateIED.sqf
  addons/modules/functions/fnc_moduleCreateMinefield.sqf
  addons/modules/functions/fnc_moduleEarthquake.sqf
  addons/modules/functions/fnc_moduleGarrison.sqf
  addons/modules/functions/fnc_modulePatrolArea.sqf
  addons/modules/functions/fnc_moduleSuicideBomber.sqf
  addons/modules/functions/fnc_moduleTurretOptics.sqf
  docs/dynamic_dialog.md
Labels: enhancement

#83 Add waypoint types config
  addons/attributes/CfgWaypointTypes.hpp
  addons/attributes/RscAttributes.hpp
  addons/attributes/XEH_PREP.hpp
  addons/attributes/XEH_preStart.sqf
  addons/attributes/config.cpp
  addons/attributes/functions/fnc_attributeWaypointType.sqf
  addons/attributes/functions/fnc_compileWaypoints.sqf
Labels: enhancement

#86 Expand player/zeus teleport context actions with teleport to vehicle capability
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_teleportIntoVehicle.sqf
  addons/common/stringtable.xml
  addons/context_actions/functions/fnc_teleportPlayers.sqf
  addons/context_actions/functions/fnc_teleportZeus.sqf
Labels: enhancement

#89 Improve side relations GUI combo selection
  addons/modules/RscAttributes.hpp
  addons/modules/functions/fnc_gui_sideRelations.sqf
Labels: enhancement

#88 Improve doors module hint when attached
  addons/doors/functions/fnc_module.sqf
Labels: enhancement

#87 Minor cleanup of tabs and includes
  addons/attributes/functions/fnc_bi_showCuratorAttributes.sqf
  addons/context_actions/functions/fnc_rearmVehicles.sqf
  addons/context_actions/functions/fnc_refuelVehicles.sqf
  addons/context_actions/functions/fnc_repairVehicles.sqf
  addons/modules/functions/fnc_moduleWeather.sqf
Labels: cleanup
