Repository zen-mod/ZEN, pull requests merged in 2019-06, with the labels that each got.

#2 Ability to ctrl + double click to remote control
  addons/attributes/functions/fnc_bi_showCuratorAttributes.sqf
  addons/remote_control/CfgEventHandlers.hpp
  addons/remote_control/XEH_PREP.hpp
  addons/remote_control/XEH_postInit.sqf
  addons/remote_control/functions/fnc_handleMouseDblClick.sqf
Labels: feature

#3 Add create target and fire mission modules
  addons/common/XEH_PREP.hpp
  addons/common/XEH_postInit.sqf
  addons/common/functions/fnc_getPhoneticName.sqf
  addons/modules/CfgVehicles.hpp
  addons/modules/RscAttributes.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/XEH_postInit.sqf
  addons/modules/config.cpp
  addons/modules/functions/fnc_gui_fireMission.sqf
  addons/modules/functions/fnc_moduleCreateTarget.sqf
  addons/modules/functions/fnc_moduleFireMission.sqf
  addons/modules/script_component.hpp
  addons/modules/stringtable.xml
  addons/modules/ui/target_ca.paa
Labels: feature

#6 Add execute code module
  addons/modules/CfgVehicles.hpp
  addons/modules/RscAttributes.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/config.cpp
  addons/modules/functions/fnc_gui_executeCode.sqf
  addons/modules/script_component.hpp
  addons/modules/stringtable.xml
  addons/modules/ui/code_ca.paa
Labels: feature

#8 Do not auto show ammo box attributes for QOL
  addons/editor/functions/fnc_bi_curatorObjectPlaced.sqf
Labels: enhancement

#9 Support missionConfigFile context menu actions
  addons/context_menu/functions/fnc_compileActions.sqf
Labels: feature

#15 Add suicide bomber module
  addons/common/XEH_postInit.sqf
  addons/modules/CfgVehicles.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/XEH_postInit.sqf
  addons/modules/config.cpp
  addons/modules/functions/fnc_moduleSuicideBomber.sqf
  addons/modules/stringtable.xml
  docs/modules_list.md
Labels: feature

#16 Add exec attribute
  addons/attributes/RscAttributes.hpp
  addons/attributes/XEH_PREP.hpp
  addons/attributes/functions/fnc_attributeExec.sqf
  addons/attributes/script_component.hpp
  addons/attributes/stringtable.xml
Labels: feature

#17 Improve reliability of land waypoint
  addons/ai/functions/fnc_waypointLand.sqf
  addons/attributes/functions/fnc_attributeWaypointType.sqf
Labels: enhancement

#18 Fix AI shooting invisible units
  addons/common/XEH_postInit.sqf
  addons/modules/functions/fnc_moduleVisibility.sqf
Labels: bug fix

#26 Fix IED objects surviving explosion
  addons/modules/functions/fnc_moduleCreateIED.sqf
Labels: bug fix

#33 Allow building with armake
  .gitignore
  addons/attributes/RscAttributes.hpp
  addons/attributes/script_component.hpp
  addons/dialog/gui.hpp
  addons/dialog/script_component.hpp
  addons/garage/script_component.hpp
  addons/inventory/script_component.hpp
  addons/main/script_macros.hpp
  addons/modules/RscAttributes.hpp
  addons/vision/script_component.hpp
  include/a3/ui_f/hpp/defineCommonGrids.inc
  include/a3/ui_f/hpp/defineDIKCodes.inc
  include/a3/ui_f/hpp/defineResincl.inc
  include/a3/ui_f_curator/ui/defineResinclDesign.inc
  include/x/cba/addons/main/script_macros_common.hpp
  include/x/cba/addons/xeh/script_xeh.hpp
  tools/setup.py
Labels: enhancement

#37 Extend camera limits
  addons/editor/XEH_preInit.sqf
  addons/editor/functions/fnc_initDisplayCurator.sqf
Labels: enhancement

#24 German translations
  AUTHORS.txt
  addons/ai/stringtable.xml
  addons/attributes/stringtable.xml
  addons/common/stringtable.xml
  addons/context_actions/stringtable.xml
  addons/context_menu/stringtable.xml
  addons/custom_modules/stringtable.xml
  addons/doors/stringtable.xml
  addons/editor/stringtable.xml
  addons/garage/stringtable.xml
  addons/main/stringtable.xml
  addons/modules/stringtable.xml
  addons/vision/stringtable.xml
Labels: translation

#27 Consistently open context menu for hovered and selected entities
  addons/context_menu/functions/fnc_openMenu.sqf
Labels: enhancement
