Repository zen-mod/ZEN, pull requests merged in 2019-08, with the labels that each got.

#91 Use hovered entity for teleport Zeus
  addons/context_actions/functions/fnc_teleportZeus.sqf
Labels: bug fix

#95 Add Eject Passengers keybind
  addons/common/XEH_PREP.hpp
  addons/common/XEH_postInit.sqf
  addons/common/functions/fnc_ejectPassengers.sqf
  addons/editor/initKeybinds.sqf
  addons/editor/stringtable.xml
Labels: feature

#100 Round artillery ETA message
  addons/modules/functions/fnc_moduleFireMission.sqf
Labels: enhancement

#49 Player visibility
  addons/visibility/$PBOPREFIX$
  addons/visibility/CfgEventHandlers.hpp
  addons/visibility/XEH_PREP.hpp
  addons/visibility/XEH_postInit.sqf
  addons/visibility/XEH_preInit.sqf
  addons/visibility/XEH_preStart.sqf
  addons/visibility/config.cpp
  addons/visibility/functions/fnc_draw.sqf
  addons/visibility/functions/fnc_start.sqf
  addons/visibility/functions/fnc_stop.sqf
  addons/visibility/functions/script_component.hpp
  addons/visibility/initSettings.sqf
  addons/visibility/script_component.hpp
  addons/visibility/stringtable.xml
Labels: feature

#110 Change garrison minimum range to 5
  addons/modules/functions/fnc_moduleGarrison.sqf
Labels: enhancement

#107 Fix independent side laser target error
  addons/modules/functions/fnc_moduleCreateTarget.sqf
Labels: bug fix

#111 Fix custom modules category showing when curator addons are changed
  addons/custom_modules/CfgFactionClasses.hpp
  addons/custom_modules/CfgVehicles.hpp
  addons/custom_modules/config.cpp
  addons/custom_modules/functions/fnc_addModules.sqf
Labels: bug fix

#112 Cache declutter empty tree faction names
  addons/editor/functions/fnc_declutterEmptyTree.sqf
Labels: optimization

#115 Add missing music tracks from the vanilla game into the Play Music module
  addons/music/$PBOPREFIX$
  addons/music/CfgMusic.hpp
  addons/music/config.cpp
  addons/music/script_component.hpp
  addons/music/stringtable.xml
Labels: enhancement

#123 Add Amount controls for flyby module, fix #121
  addons/modules/RscAttributes.hpp
  addons/modules/functions/fnc_gui_ambientFlyby.sqf
  addons/modules/functions/fnc_moduleAmbientFlyby.sqf
  addons/modules/script_component.hpp
  addons/modules/stringtable.xml
Labels: enhancement

#45 Add traits button to attributes display
  addons/attributes/RscAttributes.hpp
  addons/attributes/XEH_PREP.hpp
  addons/attributes/functions/fnc_buttonTraits.sqf
  addons/attributes/stringtable.xml
  addons/common/XEH_postInit.sqf
Labels: feature

#106 Fix artillery fire mission spread behaviour
  addons/modules/XEH_postInit.sqf
  addons/modules/functions/fnc_moduleFireMission.sqf
Labels: bug fix

#122 Add create teleporter module
  addons/common/stringtable.xml
  addons/modules/CfgVehicles.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/XEH_postInit.sqf
  addons/modules/config.cpp
  addons/modules/functions/fnc_addTeleporterAction.sqf
  addons/modules/functions/fnc_moduleCreateTeleporter.sqf
  addons/modules/functions/fnc_moduleCreateTeleporterServer.sqf
  addons/modules/script_component.hpp
  addons/modules/stringtable.xml
  docs/modules_list.md
Labels: feature

#126 Add sound to vehicle crew checkbox
  addons/editor/RscDisplayCurator.hpp
Labels: enhancement

#66 Add full arsenal
  addons/modules/CfgFactionClasses.hpp
  addons/modules/CfgVehicles.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/config.cpp
  addons/modules/functions/fnc_moduleAddFullArsenal.sqf
  addons/modules/functions/fnc_moduleRemoveArsenal.sqf
  addons/modules/stringtable.xml
Labels: feature

#120 Add Area Markers
  addons/area_markers/$PBOPREFIX$
  addons/area_markers/CfgContext.hpp
  addons/area_markers/CfgEventHandlers.hpp
  addons/area_markers/CfgVehicles.hpp
  addons/area_markers/XEH_PREP.hpp
  addons/area_markers/XEH_postInit.sqf
  addons/area_markers/XEH_preInit.sqf
  addons/area_markers/XEH_preStart.sqf
  addons/area_markers/config.cpp
  addons/area_markers/functions/fnc_applyProperties.sqf
  addons/area_markers/functions/fnc_configure.sqf
  addons/area_markers/functions/fnc_createIcon.sqf
  addons/area_markers/functions/fnc_deleteIcon.sqf
  addons/area_markers/functions/fnc_module.sqf
  addons/area_markers/functions/fnc_onKeyDown.sqf
  addons/area_markers/functions/fnc_onMouseButtonDown.sqf
  addons/area_markers/functions/fnc_onMouseButtonUp.sqf
  addons/area_markers/functions/fnc_onMouseDblClick.sqf
  addons/area_markers/functions/fnc_onMouseMoving.sqf
  addons/area_markers/functions/fnc_setIconAngle.sqf
  addons/area_markers/functions/fnc_setIconColor.sqf
  addons/area_markers/functions/fnc_update.sqf
  addons/area_markers/functions/script_component.hpp
  addons/area_markers/gui.hpp
  addons/area_markers/script_component.hpp
  addons/area_markers/stringtable.xml
  addons/common/functions/fnc_initSliderEdit.sqf
  addons/main/script_macros.hpp
  addons/modules/script_component.hpp
Labels: feature

#128 Prevent opening context menu using keybind while searching
  addons/context_menu/initKeybinds.sqf
Labels: enhancement

#119 Add paradrop waypoint
  addons/ai/functions/fnc_waypointParadrop.sqf
  addons/ai/stringtable.xml
  addons/attributes/CfgWaypointTypes.hpp
  addons/attributes/functions/fnc_compileWaypoints.sqf
Labels: feature

#130 Cleanup tabs in music component
  addons/music/CfgMusic.hpp
Labels: cleanup, ignore changelog

#125 Context menu support for dynamic children actions
  addons/context_menu/XEH_PREP.hpp
  addons/context_menu/functions/fnc_addAction.sqf
  addons/context_menu/functions/fnc_compileActions.sqf
  addons/context_menu/functions/fnc_createAction.sqf
  addons/context_menu/functions/fnc_createContextGroup.sqf
  addons/context_menu/functions/fnc_getActiveActions.sqf
  addons/context_menu/functions/fnc_openMenu.sqf
  addons/context_menu/script_component.hpp
  docs/context_menu.md
  docs/custom_modules.md
  docs/public_events.md
Labels: enhancement, refactor

#131 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other.md
Labels: ignore changelog, tools

#93 Add OWNERS control and improve Teleport Players module
  addons/attributes/RscAttributes.hpp
  addons/common/XEH_PREP.hpp
  addons/common/XEH_postInit.sqf
  addons/common/functions/fnc_getPlayers.sqf
  addons/common/functions/fnc_teleportIntoVehicle.sqf
  addons/common/stringtable.xml
  addons/dialog/XEH_PREP.hpp
  addons/dialog/functions/fnc_create.sqf
  addons/dialog/functions/fnc_gui_owners.sqf
  addons/dialog/gui.hpp
  addons/dialog/script_component.hpp
  addons/dialog/script_idc.hpp
  addons/main/script_macros.hpp
  addons/modules/CfgVehicles.hpp
  addons/modules/RscAttributes.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/XEH_postInit.sqf
  addons/modules/functions/fnc_gui_teleportPlayers.sqf
  addons/modules/functions/fnc_moduleTeleportPlayers.sqf
  addons/modules/script_component.hpp
  addons/modules/stringtable.xml
  docs/dynamic_dialog.md
Labels: enhancement

#108 Move camera to unit's position when exiting remote control
  addons/remote_control/functions/fnc_start.sqf
Labels: enhancement

#147 Add random placement parameter to Create Minefield module
  addons/modules/functions/fnc_moduleCreateMinefield.sqf
  addons/modules/stringtable.xml
Labels: enhancement

#149 Create Minefield module - Increase mine spacing at low densities
  addons/modules/functions/fnc_moduleCreateMinefield.sqf
Labels: enhancement
