Repository zen-mod/ZEN, pull requests merged in 2019-11, with the labels that each got.

#234 Add modeChanged and sideChanged editor events
  addons/editor/CfgEventHandlers.hpp
  addons/editor/XEH_PREP.hpp
  addons/editor/XEH_postInit.sqf
  addons/editor/functions/fnc_fixSideButtons.sqf
  addons/editor/functions/fnc_handleKeyDown.sqf
  addons/editor/functions/fnc_handleModeButtons.sqf
  addons/editor/functions/fnc_handleSideButtons.sqf
  addons/editor/functions/fnc_initDisplayCurator.sqf
  addons/editor/script_component.hpp
  addons/markers_tree/CfgEventHandlers.hpp
  addons/markers_tree/XEH_PREP.hpp
  addons/markers_tree/XEH_postInit.sqf
  addons/markers_tree/functions/fnc_handleKeyDown.sqf
  addons/markers_tree/functions/fnc_handleModeChange.sqf
  addons/markers_tree/functions/fnc_initDisplayCurator.sqf
  docs/frameworks/public_events.md
Labels: enhancement

#225 Portuguese translation ai, area_markers, attributes
  addons/ai/stringtable.xml
  addons/area_markers/stringtable.xml
  addons/attributes/stringtable.xml
Labels: translation

#236 Replace find substring exists check with new in syntax
  addons/dialog/functions/fnc_gui_owners.sqf
  addons/doors/functions/fnc_getDoors.sqf
  addons/garage/functions/fnc_populateLists.sqf
  addons/inventory/functions/fnc_fillList.sqf
  addons/main/script_mod.hpp
Labels: enhancement

#231 Added some Portuguese translation. #190
  addons/ai/stringtable.xml
  addons/garage/stringtable.xml
  addons/vision/stringtable.xml
Labels: translation

#237 Add Toggle Editable Icons keybind
  addons/editor/functions/fnc_handleObjectPlaced.sqf
  addons/editor/functions/fnc_initDisplayCurator.sqf
  addons/editor/initKeybinds.sqf
  addons/editor/stringtable.xml
Labels: feature

#239 Fix vision modes hint overlap with clock
  addons/vision/RscTitles.hpp
Labels: bug fix

#235 Updated Italian translation
  addons/attributes/stringtable.xml
  addons/camera/stringtable.xml
  addons/common/stringtable.xml
  addons/context_actions/stringtable.xml
  addons/main/stringtable.xml
  addons/visibility/stringtable.xml
  extras/blank/stringtable.xml
Labels: translation

#233 Add Czech translations
  addons/ai/stringtable.xml
  addons/area_markers/stringtable.xml
  addons/attributes/stringtable.xml
  addons/camera/stringtable.xml
  addons/common/stringtable.xml
  extras/blank/stringtable.xml
Labels: translation

#217 Added more Polish translations
  addons/ai/stringtable.xml
  addons/area_markers/stringtable.xml
  addons/attributes/stringtable.xml
  addons/camera/stringtable.xml
  addons/editor/stringtable.xml
  addons/garage/stringtable.xml
  addons/modules/stringtable.xml
  addons/music/stringtable.xml
  addons/visibility/stringtable.xml
Labels: translation

#216 Added some italian words
  addons/ai/stringtable.xml
  addons/area_markers/stringtable.xml
  addons/attributes/stringtable.xml
  addons/camera/stringtable.xml
  addons/common/stringtable.xml
  addons/context_actions/stringtable.xml
Labels: translation

#248 Add right click to clear to engine search bar
  addons/editor/functions/fnc_initDisplayCurator.sqf
Labels: enhancement

#246 Add meta.cpp file, steam workshop support
  Makefile
  meta.cpp
  tools/make.py
Labels: enhancement

#209 Add French translations
  addons/ai/stringtable.xml
  addons/area_markers/stringtable.xml
  addons/attributes/stringtable.xml
  addons/camera/stringtable.xml
  addons/common/stringtable.xml
  addons/context_actions/stringtable.xml
  addons/context_menu/stringtable.xml
  addons/custom_modules/stringtable.xml
  addons/doors/stringtable.xml
  addons/editor/stringtable.xml
  addons/garage/stringtable.xml
  addons/main/stringtable.xml
  addons/music/stringtable.xml
  addons/visibility/stringtable.xml
  addons/vision/stringtable.xml
Labels: translation

#249 Remove a duplicate stringtable entry in garage
  addons/garage/stringtable.xml
Labels: bug fix, ignore changelog

#238 Various changes to documentation styling
  README.md
  docs/assets/styles.css
  docs/development/coding_guidelines.md
  docs/frameworks/context_menu.md
  docs/frameworks/custom_modules.md
  docs/frameworks/public_events.md
Labels: documentation

#214 Improve object editing (vehicle in vehicle cargo, jet sounds setting)
  addons/common/XEH_postInit.sqf
  addons/editor/CfgFunctions.hpp
  addons/editor/functions/fnc_bi_curatorObjectEdited.sqf
  addons/editor/initSettings.sqf
  addons/editor/stringtable.xml
Labels: enhancement

#240 Fix group trees preventing editable icon selection
  addons/editor/functions/fnc_initDisplayCurator.sqf
Labels: feature

#241 Add Toggle Lamps module
  addons/common/XEH_PREP.hpp
  addons/common/XEH_postInit.sqf
  addons/common/functions/fnc_getLightingSelections.sqf
  addons/common/functions/fnc_setLampState.sqf
  addons/common/stringtable.xml
  addons/modules/CfgVehicles.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/config.cpp
  addons/modules/functions/fnc_moduleToggleLamps.sqf
  addons/modules/stringtable.xml
  addons/modules/ui/street_lamp_ca.paa
  docs/user_guide/modules_list.md
Labels: feature

#242 Restore previous map state on display load
  addons/editor/CfgEventHandlers.hpp
  addons/editor/XEH_PREP.hpp
  addons/editor/XEH_postInit.sqf
  addons/editor/functions/fnc_handleLoad.sqf
  addons/editor/functions/fnc_handleUnload.sqf
Labels: feature

#219 Add Deep Copy/Paste keybinds
  addons/common/XEH_PREP.hpp
  addons/common/XEH_postInit.sqf
  addons/common/functions/fnc_deserializeInventory.sqf
  addons/common/functions/fnc_getPosFromScreen.sqf
  addons/common/functions/fnc_getPylonTurret.sqf
  addons/common/functions/fnc_serializeInventory.sqf
  addons/editor/XEH_PREP.hpp
  addons/editor/XEH_preInit.sqf
  addons/editor/functions/fnc_deepCopy.sqf
  addons/editor/functions/fnc_deepPaste.sqf
  addons/editor/initKeybinds.sqf
  addons/editor/stringtable.xml
Labels: feature

#244 Add function to remove context menu actions
  addons/context_menu/XEH_PREP.hpp
  addons/context_menu/functions/fnc_removeAction.sqf
  docs/frameworks/context_menu.md
Labels: feature

#250 Add stringtable validation tool
  azure-pipelines.yml
  tools/stringtable_validator.py
Labels: ignore changelog, tools

#247 Add editor preview images displaying
  README.md
  addons/editor_previews/$PBOPREFIX$
  addons/editor_previews/CfgEventHandlers.hpp
  addons/editor_previews/XEH_PREP.hpp
  addons/editor_previews/XEH_postInit.sqf
  addons/editor_previews/XEH_preInit.sqf
  addons/editor_previews/XEH_preStart.sqf
  addons/editor_previews/config.cpp
  addons/editor_previews/functions/fnc_handleMouseExit.sqf
  addons/editor_previews/functions/fnc_handleMouseUpdate.sqf
  addons/editor_previews/functions/fnc_initDisplayCurator.sqf
  addons/editor_previews/functions/script_component.hpp
  addons/editor_previews/gui.hpp
  addons/editor_previews/initSettings.sqf
  addons/editor_previews/script_component.hpp
  addons/editor_previews/stringtable.xml
  docs/home.md
Labels: feature

#255 Fix drawIcon3D icons being hidden after using VA
  addons/common/XEH_postInit.sqf
Labels: bug fix

#226 Improve garage tabs handling
  addons/garage/XEH_preInit.sqf
  addons/garage/functions/fnc_onKeyDown.sqf
  addons/garage/functions/fnc_onMouseButtonClick.sqf
  addons/garage/functions/fnc_onTabSelect.sqf
  addons/garage/functions/fnc_openGarage.sqf
  addons/garage/functions/fnc_populateLists.sqf
  addons/garage/gui.hpp
Labels: enhancement

#189 Use CBA_fnc_turretEvent
  addons/common/XEH_postInit.sqf
  addons/common/functions/fnc_setVehicleAmmo.sqf
  addons/main/script_mod.hpp
Labels: enhancement

#211 Add Spawn Reinforcements module
  addons/ai/functions/fnc_waypointLand.sqf
  addons/ai/stringtable.xml
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_getCargoPositionsCount.sqf
  addons/common/functions/fnc_getVehicleAmmo.sqf
  addons/common/functions/fnc_getVehicleIcon.sqf
  addons/common/stringtable.xml
  addons/modules/CfgFactionClasses.hpp
  addons/modules/CfgVehicles.hpp
  addons/modules/RscAttributes.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/XEH_postInit.sqf
  addons/modules/XEH_preInit.sqf
  addons/modules/XEH_preStart.sqf
  addons/modules/config.cpp
  addons/modules/functions/fnc_compileReinforcements.sqf
  addons/modules/functions/fnc_gui_fireMission.sqf
  addons/modules/functions/fnc_gui_spawnReinforcements.sqf
  addons/modules/functions/fnc_moduleAmbientFlyby.sqf
  addons/modules/functions/fnc_moduleCreateLZ.sqf
  addons/modules/functions/fnc_moduleCreateRP.sqf
  addons/modules/functions/fnc_moduleCreateTarget.sqf
  addons/modules/functions/fnc_modulePatrolArea.sqf
  addons/modules/functions/fnc_moduleSpawnReinforcements.sqf
  addons/modules/script_component.hpp
  addons/modules/stringtable.xml
  addons/modules/ui/person_ca.paa
  addons/modules/ui/rp_ca.paa
  addons/position_logics/$PBOPREFIX$
  addons/position_logics/CfgEventHandlers.hpp
  addons/position_logics/XEH_PREP.hpp
  addons/position_logics/XEH_preInit.sqf
  addons/position_logics/XEH_preStart.sqf
  addons/position_logics/config.cpp
  addons/position_logics/functions/fnc_add.sqf
  addons/position_logics/functions/fnc_exists.sqf
  addons/position_logics/functions/fnc_get.sqf
  addons/position_logics/functions/fnc_initList.sqf
  addons/position_logics/functions/fnc_nextName.sqf
  addons/position_logics/functions/fnc_select.sqf
  addons/position_logics/functions/script_component.hpp
  addons/position_logics/script_component.hpp
  addons/position_logics/stringtable.xml
  addons/position_logics/ui/farthest_ca.paa
  addons/position_logics/ui/nearest_ca.paa
  addons/position_logics/ui/random_ca.paa
  docs/user_guide/modules_list.md
Labels: feature

#243 Add Editable Objects context menu action
  addons/common/stringtable.xml
  addons/context_actions/CfgContext.hpp
  addons/context_actions/XEH_PREP.hpp
  addons/context_actions/functions/fnc_editableObjects.sqf
  addons/context_actions/stringtable.xml
  addons/context_actions/ui/add_ca.paa
  addons/context_actions/ui/remove_ca.paa
  docs/user_guide/context_actions.md
Labels: feature

#252 Added Japanese translation
  addons/ai/stringtable.xml
  addons/area_markers/stringtable.xml
  addons/attributes/stringtable.xml
  addons/camera/stringtable.xml
  addons/common/stringtable.xml
  addons/context_actions/stringtable.xml
  addons/context_menu/stringtable.xml
  addons/custom_modules/stringtable.xml
  addons/doors/stringtable.xml
  addons/editor/stringtable.xml
  addons/garage/stringtable.xml
  addons/main/stringtable.xml
  addons/modules/stringtable.xml
  addons/music/stringtable.xml
  addons/visibility/stringtable.xml
  addons/vision/stringtable.xml
Labels: translation

#258 Fix adding reinforcements to editable objects
  addons/modules/functions/fnc_moduleSpawnReinforcements.sqf
Labels: bug fix

#263 Stringtable validator improvements
  tools/stringtable_validator.py
Labels: ignore changelog, tools
