Repository zen-mod/ZEN, pull requests merged in 2019-09, with the labels that each got.

#153 Add alive check to stance context menu action
  addons/context_actions/CfgContext.hpp
  addons/context_actions/functions/fnc_setStance.sqf
Labels: enhancement

#135 Visibility indicator tweaks
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_isInScreenshotMode.sqf
  addons/visibility/functions/fnc_draw.sqf
  addons/visibility/initSettings.sqf
  addons/visibility/stringtable.xml
Labels: enhancement

#129 Add Deploy Countermeasures keybind
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_deployCountermeasures.sqf
  addons/editor/initKeybinds.sqf
  addons/editor/stringtable.xml
Labels: feature

#155 Fix initSliderEdit not dividing percentage input
  addons/common/functions/fnc_initSliderEdit.sqf
Labels: bug fix

#157 Add unscheduled earthquake function
  addons/common/XEH_PREP.hpp
  addons/common/XEH_postInit.sqf
  addons/common/functions/fnc_earthquake.sqf
  addons/modules/XEH_postInit.sqf
  addons/modules/functions/fnc_moduleEarthquake.sqf
Labels: enhancement

#159 Add portrait entry for Smoke Pillar module
  addons/modules/CfgVehicles.hpp
Labels: enhancement

#162 Add Toggle Flashlights module
  addons/common/XEH_postInit.sqf
  addons/common/stringtable.xml
  addons/modules/CfgVehicles.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/config.cpp
  addons/modules/functions/fnc_moduleToggleFlashlights.sqf
  addons/modules/stringtable.xml
  addons/modules/ui/flashlight_ca.paa
Labels: feature

#140 Improve vehicle ammo functions
  addons/common/XEH_PREP.hpp
  addons/common/XEH_postInit.sqf
  addons/common/functions/fnc_getTurretMagazines.sqf
  addons/common/functions/fnc_getVehicleAmmo.sqf
  addons/common/functions/fnc_setMagazineAmmo.sqf
  addons/common/functions/fnc_setTurretAmmo.sqf
  addons/common/functions/fnc_setVehicleAmmo.sqf
Labels: enhancement

#163 Add icons to heal children actions, Move player action up
  addons/context_actions/CfgContext.hpp
  addons/context_actions/functions/fnc_healUnits.sqf
  addons/context_actions/script_component.hpp
  addons/modules/CfgFactionClasses.hpp
  addons/modules/stringtable.xml
Labels: enhancement

#167 Initially open garage at max distance
  addons/garage/XEH_preInit.sqf
  addons/garage/functions/fnc_onMouseZChanged.sqf
Labels: enhancement

#169 Fix incorrect position format in moduleFireMission
  addons/modules/functions/fnc_moduleFireMission.sqf
Labels: bug fix

#170 Improve copy paste action icons
  addons/context_actions/ui/copy_ca.paa
  addons/context_actions/ui/paste_ca.paa
Labels: enhancement

#176 Fix Set Date module year synchronization
  addons/common/XEH_postInit.sqf
  addons/modules/functions/fnc_gui_setDate.sqf
Labels: bug fix

#174 Add selection saving to Ambient Flyby dialog
  addons/modules/functions/fnc_gui_ambientFlyby.sqf
Labels: enhancement

#175 Add selection saving to Update Editable Objects dialog
  addons/modules/functions/fnc_gui_editableObjects.sqf
Labels: enhancement

#168 Add context menu actions to copy/paste vehicle appearance
  addons/context_actions/CfgContext.hpp
  addons/context_actions/XEH_preInit.sqf
Labels: feature

#172 Keep factions visible when clicking the collapse all button
  addons/editor/functions/fnc_handleTreeButtons.sqf
Labels: enhancement

#182 Fix hidden garage DLC icon showing when interface is toggled
  addons/garage/functions/fnc_showVehicleInfo.sqf
Labels: bug fix
