Repository zen-mod/ZEN, pull requests merged in 2020-04, with the labels that each got.

#318 Add return type validator for SQF files
  addons/context_actions/functions/fnc_canHealUnits.sqf
  addons/context_menu/functions/fnc_compileActions.sqf
  addons/doors/functions/fnc_getState.sqf
  addons/editor/functions/fnc_handleSearchClick.sqf
  azure-pipelines.yml
  tools/return_checker.py
Labels: ignore changelog, tools

#316 Add release drafter CI
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: ignore changelog, tools

#349 Fix issue with label arrays
  .github/release-drafter.yml
Labels: ignore changelog, tools

#343 Add careless option to Patrol Area module
  addons/common/stringtable.xml
  addons/modules/functions/fnc_modulePatrolArea.sqf
Labels: enhancement

#353 Fix release drafter category titles and change template
  .github/release-drafter.yml
Labels: ignore changelog, tools

#341 Add more animation options to Ambient Animation module
  addons/modules/functions/fnc_moduleAmbientAnim.sqf
  addons/modules/functions/fnc_moduleAmbientAnimStart.sqf
  addons/modules/stringtable.xml
Labels: enhancement

#348 Improve editor trees scroll bar visuals
  addons/editor/RscDisplayCurator.hpp
Labels: enhancement

#351 Sort players alphabetically in OWNERS control
  addons/dialog/functions/fnc_gui_owners.sqf
Labels: enhancement

#352 Add icon for Light Source module
  addons/modules/CfgVehicles.hpp
  addons/modules/ui/light_ca.paa
Labels: enhancement

#356 Add new chairs to Sit On Chair module
  addons/modules/functions/fnc_moduleSitOnChair.sqf
Labels: enhancement

#357 Fix japanese typo
  addons/common/stringtable.xml
Labels: bug fix, ignore changelog

#359 Add Thing type objects to Editable Objects module Static filter
  addons/modules/functions/fnc_moduleEditableObjects.sqf
Labels: enhancement

#350 Add Korean translations
  addons/ai/stringtable.xml
  addons/area_markers/stringtable.xml
  addons/attributes/stringtable.xml
  addons/camera/stringtable.xml
  addons/common/stringtable.xml
  addons/context_actions/stringtable.xml
  addons/doors/stringtable.xml
  addons/editor/stringtable.xml
  addons/modules/stringtable.xml
  extras/blank/stringtable.xml
  optionals/compat_ace/stringtable.xml
Labels: translation

#355 Use ZEN remote control in ACE interaction menu action
  optionals/compat_ace/ACE_ZeusActions.hpp
  optionals/compat_ace/XEH_PREP.hpp
  optionals/compat_ace/XEH_preInit.sqf
  optionals/compat_ace/XEH_preStart.sqf
  optionals/compat_ace/config.cpp
  optionals/compat_ace/functions/fnc_canRemoteControl.sqf
  optionals/compat_ace/functions/fnc_remoteControl.sqf
  optionals/compat_ace/functions/script_component.hpp
Labels: enhancement

#365 Create a new component easier via a Python tool
  tools/new_component.py
Labels: ignore changelog, tools

#366 Show unit name in Chatter dialog title
  addons/modules/functions/fnc_moduleChatter.sqf
Labels: enhancement
