Repository zen-mod/ZEN, pull requests merged in 2020-06, with the labels that each got.

#328 Add Atomic Bomb module
  AUTHORS.txt
  addons/modules/CfgVehicles.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/XEH_postInit.sqf
  addons/modules/config.cpp
  addons/modules/functions/fnc_moduleNuke.sqf
  addons/modules/functions/fnc_moduleNukeLocal.sqf
  addons/modules/stringtable.xml
  addons/modules/ui/nuke_ca.paa
  docs/user_guide/modules_list.md
Labels: feature

#400 Fix intel module, Copy dialog values when saving
  addons/dialog/functions/fnc_close.sqf
Labels: bug fix, ignore changelog

#401 Added Discord badge to README
  README.md
Labels: enhancement, ignore changelog

#416 Stringtable Validator - Print parsing error exception
  tools/stringtable_validator.py
Labels: ignore changelog, tools

#414 Fix default inventories cache being modified by reference
  addons/common/functions/fnc_getDefaultInventory.sqf
Labels: bug fix
