Repository zen-mod/ZEN, pull requests merged in 2020-02, with the labels that each got.

#254 Add Custom Fire module
  addons/dialog/functions/fnc_create.sqf
  addons/modules/CfgVehicles.hpp
  addons/modules/RscAttributes.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/XEH_postInit.sqf
  addons/modules/config.cpp
  addons/modules/functions/fnc_moduleEffectFire.sqf
  addons/modules/functions/fnc_moduleEffectFireLocal.sqf
  addons/modules/functions/fnc_moduleLightSource.sqf
  addons/modules/stringtable.xml
  addons/modules/ui/fire_ca.paa
  docs/user_guide/modules_list.md
Labels: feature

#47 Object placement preview
  README.md
  addons/editor/functions/fnc_handleSideButtons.sqf
  addons/placement/$PBOPREFIX$
  addons/placement/CfgEventHandlers.hpp
  addons/placement/XEH_PREP.hpp
  addons/placement/XEH_postInit.sqf
  addons/placement/XEH_preInit.sqf
  addons/placement/XEH_preStart.sqf
  addons/placement/config.cpp
  addons/placement/functions/fnc_handleObjectPlaced.sqf
  addons/placement/functions/fnc_handleTreeChange.sqf
  addons/placement/functions/fnc_handleTreeSelect.sqf
  addons/placement/functions/fnc_setupPreview.sqf
  addons/placement/functions/fnc_updatePreview.sqf
  addons/placement/functions/script_component.hpp
  addons/placement/initSettings.sqf
  addons/placement/script_component.hpp
  addons/placement/stringtable.xml
  docs/home.md
Labels: feature

#296 Add Russian translations
  addons/ai/stringtable.xml
  addons/area_markers/stringtable.xml
  addons/attributes/stringtable.xml
  addons/camera/stringtable.xml
  extras/blank/stringtable.xml
Labels: translation

#286 Improve context menu action configs and UX
  AUTHORS.txt
  addons/area_markers/CfgContext.hpp
  addons/common/functions/fnc_teleportIntoVehicle.sqf
  addons/context_actions/CfgContext.hpp
  addons/context_actions/XEH_PREP.hpp
  addons/context_actions/config.cpp
  addons/context_actions/functions/fnc_canEditInventory.sqf
  addons/context_actions/functions/fnc_canEditLoadout.sqf
  addons/context_actions/functions/fnc_canEditVehicleAppearance.sqf
  addons/context_actions/functions/fnc_canHealUnits.sqf
  addons/context_actions/functions/fnc_canPasteVehicleAppearance.sqf
  addons/context_actions/functions/fnc_canRearmVehicles.sqf
  addons/context_actions/functions/fnc_canRefuelVehicles.sqf
  addons/context_actions/functions/fnc_canRepairVehicles.sqf
  addons/context_actions/functions/fnc_copyVehicleAppearance.sqf
  addons/context_actions/functions/fnc_healUnits.sqf
  addons/context_actions/functions/fnc_pasteVehicleAppearance.sqf
  addons/context_actions/functions/fnc_rearmVehicles.sqf
  addons/context_actions/functions/fnc_refuelVehicles.sqf
  addons/context_actions/functions/fnc_repairVehicles.sqf
  addons/context_actions/functions/fnc_setBehaviour.sqf
  addons/context_actions/functions/fnc_setCombatMode.sqf
  addons/context_actions/functions/fnc_setFormation.sqf
  addons/context_actions/functions/fnc_setSpeed.sqf
  addons/context_actions/functions/fnc_setSpeedMode.sqf
  addons/context_actions/functions/fnc_setStance.sqf
  addons/context_actions/functions/fnc_teleportPlayers.sqf
  addons/context_actions/functions/fnc_teleportZeus.sqf
  addons/context_actions/stringtable.xml
  addons/context_actions/ui/attack_ca.paa
  addons/context_actions/ui/defend_ca.paa
  addons/context_actions/ui/engage_ca.paa
  addons/context_actions/ui/hold_ca.paa
  addons/context_menu/functions/fnc_compileActions.sqf
  addons/context_menu/functions/fnc_initDisplayCurator.sqf
  addons/context_menu/script_component.hpp
  addons/main/script_mod.hpp
  addons/remote_control/CfgContext.hpp
  addons/remote_control/config.cpp
  addons/remote_control/functions/fnc_canControl.sqf
  docs/frameworks/context_menu.md
Labels: enhancement

#298 German translation
  addons/ai/stringtable.xml
  addons/attributes/stringtable.xml
  addons/common/stringtable.xml
  addons/context_actions/stringtable.xml
  addons/damage/stringtable.xml
  addons/editor/stringtable.xml
  addons/editor_previews/stringtable.xml
  addons/garage/stringtable.xml
  addons/inventory/stringtable.xml
  addons/modules/stringtable.xml
  addons/music/stringtable.xml
  addons/placement/stringtable.xml
  addons/position_logics/stringtable.xml
Labels: translation

#299 Fix intel action not adding an intel entry
  addons/modules/functions/fnc_addIntelAction.sqf
Labels: bug fix

#40 VLS support for artillery module
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_fireVLS.sqf
  addons/common/functions/fnc_getArtilleryETA.sqf
  addons/common/functions/fnc_getWeaponReloadTime.sqf
  addons/common/functions/fnc_isVLS.sqf
  addons/common/functions/fnc_loadMagazineInstantly.sqf
  addons/common/script_component.hpp
  addons/modules/XEH_postInit.sqf
  addons/modules/functions/fnc_gui_fireMission.sqf
  addons/modules/functions/fnc_moduleFireMission.sqf
Labels: enhancement

#304 Fix decimal input for Change Height module
  addons/modules/CfgVehicles.hpp
  addons/modules/functions/fnc_moduleChangeHeight.sqf
  addons/modules/stringtable.xml
Labels: bug fix

#307 Improve fastrope waypoint height handling
  addons/ai/functions/fnc_waypointFastrope.sqf
  addons/ai/functions/fnc_waypointLand.sqf
  addons/ai/functions/fnc_waypointParadrop.sqf
Labels: enhancement

#278 Toggle ACE captive and surrender via context menu
  AUTHORS.txt
  addons/context_actions/CfgContext.hpp
  addons/context_actions/XEH_PREP.hpp
  addons/context_actions/functions/fnc_canToggleSurrender.sqf
  addons/context_actions/functions/fnc_toggleCaptive.sqf
  addons/context_actions/functions/fnc_toggleSurrender.sqf
  addons/context_actions/stringtable.xml
Labels: feature

#306 Add Camera Flashlight
  README.md
  addons/flashlight/$PBOPREFIX$
  addons/flashlight/CfgEventHandlers.hpp
  addons/flashlight/XEH_PREP.hpp
  addons/flashlight/XEH_postInit.sqf
  addons/flashlight/XEH_preInit.sqf
  addons/flashlight/XEH_preStart.sqf
  addons/flashlight/config.cpp
  addons/flashlight/functions/fnc_toggle.sqf
  addons/flashlight/functions/script_component.hpp
  addons/flashlight/initKeybinds.sqf
  addons/flashlight/script_component.hpp
  addons/flashlight/stringtable.xml
  docs/home.md
Labels: feature

#308 Move editor settings under own subcategory
  addons/camera/initSettings.sqf
  addons/camera/stringtable.xml
  addons/common/initSettings.sqf
  addons/common/stringtable.xml
  addons/context_menu/initKeybinds.sqf
  addons/context_menu/initSettings.sqf
  addons/editor/initKeybinds.sqf
  addons/editor/initSettings.sqf
  addons/editor/stringtable.xml
  addons/editor_previews/initSettings.sqf
  addons/main/stringtable.xml
  addons/placement/initSettings.sqf
  addons/visibility/initSettings.sqf
  addons/vision/initKeybinds.sqf
  addons/vision/initSettings.sqf
  addons/vision/stringtable.xml
Labels: enhancement

#279 Add Fire Artillery context menu action
  addons/common/XEH_PREP.hpp
  addons/common/XEH_preInit.sqf
  addons/common/functions/fnc_getTargetPos.sqf
  addons/common/functions/fnc_selectPosition.sqf
  addons/common/functions/fnc_showMessage.sqf
  addons/common/script_component.hpp
  addons/context_actions/CfgContext.hpp
  addons/context_actions/XEH_PREP.hpp
  addons/context_actions/functions/fnc_getArtilleryActions.sqf
  addons/context_actions/functions/fnc_selectArtilleryPos.sqf
  addons/context_actions/functions/fnc_teleportPlayers.sqf
  addons/context_actions/stringtable.xml
  addons/context_actions/ui/ammo_ca.paa
  addons/modules/functions/fnc_moduleAttachTo.sqf
Labels: feature

#245 Add optional ACE compatibility PBO
  addons/modules/functions/fnc_bi_moduleMine.sqf
  optionals/compat_ace/$PBOPREFIX$
  optionals/compat_ace/CfgEventHandlers.hpp
  optionals/compat_ace/CfgVehicles.hpp
  optionals/compat_ace/XEH_preInit.sqf
  optionals/compat_ace/config.cpp
  optionals/compat_ace/initSettings.sqf
  optionals/compat_ace/script_component.hpp
  optionals/compat_ace/stringtable.xml
Labels: feature
