Repository zen-mod/ZEN, pull requests merged in 2020-05, with the labels that each got.

#161 Add display to configure vehicle magazine loadouts
  addons/loadout/$PBOPREFIX$
  addons/loadout/CfgEventHandlers.hpp
  addons/loadout/XEH_PREP.hpp
  addons/loadout/XEH_preInit.sqf
  addons/loadout/XEH_preStart.sqf
  addons/loadout/config.cpp
  addons/loadout/functions/fnc_clear.sqf
  addons/loadout/functions/fnc_configure.sqf
  addons/loadout/functions/fnc_confirm.sqf
  addons/loadout/functions/fnc_fillList.sqf
  addons/loadout/functions/fnc_getWeaponList.sqf
  addons/loadout/functions/fnc_getWeaponName.sqf
  addons/loadout/functions/fnc_keyDown.sqf
  addons/loadout/functions/fnc_modify.sqf
  addons/loadout/functions/fnc_updateButtons.sqf
  addons/loadout/functions/script_component.hpp
  addons/loadout/gui.hpp
  addons/loadout/script_component.hpp
  addons/loadout/stringtable.xml
Labels: feature

#364 Add Rotate Object module
  addons/common/stringtable.xml
  addons/modules/CfgVehicles.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/XEH_postInit.sqf
  addons/modules/config.cpp
  addons/modules/functions/fnc_moduleRotateObject.sqf
  addons/modules/stringtable.xml
  addons/modules/ui/rotate_ca.paa
Labels: feature

#375 Fix preserving unit sides in deserialize objects function
  addons/common/functions/fnc_deserializeObjects.sqf
Labels: bug fix

#368 Add attributes display to change AI abilities
  addons/ai/stringtable.xml
  addons/attributes/XEH_postInit.sqf
  addons/attributes/functions/fnc_gui_checkboxes.sqf
  addons/attributes/initAttributes.sqf
  addons/attributes/script_component.hpp
  addons/attributes/stringtable.xml
Labels: feature

#369 Fix incorrect upper limit in addGroupIcons loops
  addons/editor/functions/fnc_addGroupIcons.sqf
Labels: bug fix

#363 Add execution mode button to exec attributes
  addons/attributes/functions/fnc_gui_code.sqf
  addons/attributes/gui.hpp
  addons/attributes/initAttributes.sqf
  addons/attributes/script_component.hpp
  addons/attributes/stringtable.xml
Labels: enhancement

#380 Add support for unit insignias in serializing functions
  addons/common/functions/fnc_deserializeObjects.sqf
  addons/common/functions/fnc_serializeObjects.sqf
Labels: enhancement

#383 Switch icon order of Engine and Lights attributes
  addons/attributes/initAttributes.sqf
Labels: enhancement

#388 Preserve magazine ammo counts in serializing functions
  addons/common/functions/fnc_deserializeInventory.sqf
  addons/common/functions/fnc_serializeInventory.sqf
Labels: bug fix

#385 Unlock Old Man Music
  addons/music/CfgMusic.hpp
  addons/music/stringtable.xml
Labels: feature

#395 Action sound and more classes for intel
  addons/modules/functions/fnc_addIntelAction.sqf
  addons/modules/functions/fnc_moduleCreateIntel.sqf
  addons/modules/stringtable.xml
Labels: enhancement

#397 Add reset button to inventory display
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_getDefaultInventory.sqf
  addons/common/functions/fnc_hasDefaultInventory.sqf
  addons/inventory/XEH_PREP.hpp
  addons/inventory/functions/fnc_configure.sqf
  addons/inventory/functions/fnc_reset.sqf
  addons/inventory/gui.hpp
  addons/inventory/script_component.hpp
  addons/inventory/stringtable.xml
  addons/inventory/ui/reset_ca.paa
Labels: feature

#374 Rework and improve dialog component
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_initDisplayPositioning.sqf
  addons/common/functions/fnc_initOwnersControl.sqf
  addons/common/functions/fnc_initSidesControl.sqf
  addons/common/functions/fnc_initSliderEdit.sqf
  addons/common/gui.hpp
  addons/common/script_component.hpp
  addons/common/stringtable.xml
  addons/common/ui/check_all_ca.paa
  addons/common/ui/uncheck_all_ca.paa
  addons/dialog/XEH_PREP.hpp
  addons/dialog/functions/fnc_close.sqf
  addons/dialog/functions/fnc_create.sqf
  addons/dialog/functions/fnc_gui_cancel.sqf
  addons/dialog/functions/fnc_gui_checkbox.sqf
  addons/dialog/functions/fnc_gui_color.sqf
  addons/dialog/functions/fnc_gui_combo.sqf
  addons/dialog/functions/fnc_gui_confirm.sqf
  addons/dialog/functions/fnc_gui_edit.sqf
  addons/dialog/functions/fnc_gui_list.sqf
  addons/dialog/functions/fnc_gui_owners.sqf
  addons/dialog/functions/fnc_gui_sides.sqf
  addons/dialog/functions/fnc_gui_slider.sqf
  addons/dialog/functions/fnc_gui_toolbox.sqf
  addons/dialog/functions/fnc_gui_vector.sqf
  addons/dialog/gui.hpp
  addons/dialog/script_component.hpp
  addons/dialog/script_idc.hpp
Labels: enhancement

#376 Improve Game Master module initialization
  addons/common/XEH_PREP.hpp
  addons/common/XEH_postInit.sqf
  addons/common/XEH_preInit.sqf
  addons/common/functions/fnc_runAfterSettingsInit.sqf
  addons/common/initSettings.sqf
  addons/common/stringtable.xml
  addons/modules/CfgVehicles.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/functions/fnc_bi_moduleCurator.sqf
  optionals/compat_ace/CfgVehicles.hpp
Labels: enhancement

#379 Add Orient to Terrain Normal keybind
  addons/common/XEH_postInit.sqf
  addons/editor/initKeybinds.sqf
  addons/editor/stringtable.xml
Labels: feature

#399 Fix Old Man duplicate music class
  addons/music/CfgMusic.hpp
Labels: bug fix, ignore changelog

#361 Add Search Building module
  addons/ai/XEH_PREP.hpp
  addons/ai/functions/fnc_searchBuilding.sqf
  addons/common/XEH_postInit.sqf
  addons/modules/CfgVehicles.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/config.cpp
  addons/modules/functions/fnc_moduleSearchBuilding.sqf
  addons/modules/stringtable.xml
Labels: feature
