Repository zen-mod/ZEN, pull requests merged in 2020-10, with the labels that each got.

#469 Clear previous selection in Teleport Players module
  addons/modules/functions/fnc_moduleTeleportPlayers.sqf
Labels: enhancement

#472 Fix teleporting onto surfaces using context menu actions
  addons/context_actions/functions/fnc_teleportPlayers.sqf
  addons/context_actions/functions/fnc_teleportZeus.sqf
Labels: bug fix

#475 Use public CBA_fnc_addSetting instead of internal CBA_settings_fnc_init
  addons/camera/initSettings.sqf
  addons/common/initSettings.sqf
  addons/context_menu/initSettings.sqf
  addons/editor/initSettings.sqf
  addons/editor_previews/initSettings.sqf
  addons/placement/initSettings.sqf
  addons/visibility/initSettings.sqf
  addons/vision/initSettings.sqf
  optionals/compat_ace/initSettings.sqf
Labels: cleanup

#476 Fix hasDefaultInventory function incorrectly handling item cargo
  addons/common/functions/fnc_hasDefaultInventory.sqf
Labels: bug fix

#478 Fix include crew panel positioning
  addons/editor/RscDisplayCurator.hpp
Labels: bug fix

#479 Fix attributes checkboxes control font size
  addons/attributes/functions/fnc_gui_checkboxes.sqf
Labels: bug fix

#474 Switch argument order in execute code module
  addons/modules/functions/fnc_gui_executeCode.sqf
  addons/modules/stringtable.xml
Labels: enhancement

#482 use configOf instead of typeOf config lookup
  addons/ai/functions/fnc_waypointFastrope.sqf
  addons/attributes/functions/fnc_bi_showCuratorAttributes.sqf
  addons/attributes/functions/fnc_open.sqf
  addons/attributes/initAttributes.sqf
  addons/common/functions/fnc_deserializeObjects.sqf
  addons/common/functions/fnc_exportMissionSQF.sqf
  addons/common/functions/fnc_getPylonTurret.sqf
  addons/context_actions/functions/fnc_canEditInventory.sqf
  addons/custom_modules/functions/fnc_init.sqf
  addons/damage/functions/fnc_configure.sqf
  addons/doors/functions/fnc_getDoors.sqf
  addons/editor/functions/fnc_bi_curatorObjectPlaced.sqf
  addons/garage/functions/fnc_populateLists.sqf
  addons/garage/functions/fnc_showVehicleInfo.sqf
  addons/inventory/XEH_preInit.sqf
  addons/inventory/functions/fnc_configure.sqf
  addons/loadout/functions/fnc_configure.sqf
  addons/main/script_mod.hpp
  addons/modules/functions/fnc_bi_moduleMine.sqf
  addons/modules/functions/fnc_gui_cas.sqf
  addons/modules/functions/fnc_gui_damageBuildings.sqf
  addons/modules/functions/fnc_initDisplay.sqf
  addons/modules/functions/fnc_initModule.sqf
  addons/modules/functions/fnc_moduleDamageBuildings.sqf
  addons/pylons/functions/fnc_configure.sqf
Labels: optimization
