Repository zen-mod/ZEN, pull requests merged in 2020-08, with the labels that each got.

#446 Improve context menu handling of long action names
  addons/context_menu/XEH_PREP.hpp
  addons/context_menu/functions/fnc_close.sqf
  addons/context_menu/functions/fnc_compileActions.sqf
  addons/context_menu/functions/fnc_createContextGroup.sqf
  addons/context_menu/functions/fnc_initDisplayCurator.sqf
  addons/context_menu/functions/fnc_open.sqf
  addons/context_menu/gui.hpp
  addons/context_menu/initKeybinds.sqf
  addons/context_menu/script_component.hpp
Labels: enhancement

#447 Remove deprecated public events
  addons/common/XEH_postInit.sqf
Labels: cleanup

#449 Optimize enableAI/disableAI target events
  addons/common/XEH_postInit.sqf
  addons/modules/functions/fnc_moduleAmbientAnimEnd.sqf
  addons/modules/functions/fnc_moduleAmbientAnimStart.sqf
Labels: optimization

#450 Various documentation updates and fixes
  docs/assets/styles.css
  docs/development/coding_guidelines.md
  docs/frameworks/context_menu.md
  docs/frameworks/custom_modules.md
  docs/index.html
  docs/user_guide/context_actions.md
  docs/user_guide/modules_list.md
Labels: documentation, ignore changelog

#451 Fix script error for incorrectly configured aircraft
  addons/modules/functions/fnc_compileAircraft.sqf
Labels: bug fix

#423 Add Crew To Gunner module
  addons/modules/CfgVehicles.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/XEH_postInit.sqf
  addons/modules/config.cpp
  addons/modules/functions/fnc_moduleCrewToGunner.sqf
  addons/modules/stringtable.xml
  docs/user_guide/modules_list.md
Labels: feature

#454 Update Korean translation
  AUTHORS.txt
  addons/ai/stringtable.xml
  addons/area_markers/stringtable.xml
  addons/attributes/stringtable.xml
  addons/camera/stringtable.xml
  addons/common/stringtable.xml
  addons/compositions/stringtable.xml
  addons/context_actions/stringtable.xml
  addons/context_menu/stringtable.xml
  addons/custom_modules/stringtable.xml
  addons/damage/stringtable.xml
  addons/editor/stringtable.xml
Labels: translation

#459 Add forced option to Change Weather module
  addons/modules/XEH_postInit.sqf
  addons/modules/functions/fnc_moduleWeather.sqf
  addons/modules/stringtable.xml
Labels: enhancement

#437 Add Open Attributes Display keybind
  addons/attributes/XEH_preInit.sqf
  addons/attributes/initKeybinds.sqf
  addons/attributes/script_component.hpp
  addons/attributes/stringtable.xml
Labels: feature

#460 Add warning for missing ACE compatibility PBO
  addons/main/CfgSettings.hpp
Labels: enhancement

#430 Open editable objects dialog when clicking main action
  addons/context_actions/CfgContext.hpp
  addons/context_actions/XEH_PREP.hpp
  addons/context_actions/functions/fnc_openEditableObjectsDialog.sqf
  addons/context_actions/functions/fnc_updateEditableObjects.sqf
Labels: enhancement

#438 Add Respawn Vehicle attribute
  addons/attributes/XEH_postInit.sqf
  addons/attributes/initAttributes.sqf
  addons/attributes/stringtable.xml
Labels: feature

#461 Fix missile magazines not being shown in inventory display
  addons/inventory/functions/fnc_preload.sqf
  addons/main/script_macros.hpp
Labels: bug fix

#439 Add loiter waypoint type
  addons/attributes/CfgWaypointTypes.hpp
  addons/attributes/XEH_PREP.hpp
  addons/attributes/functions/fnc_gui_loiter.sqf
  addons/attributes/gui.hpp
  addons/attributes/initAttributes.sqf
Labels: feature
