Repository zen-mod/ZEN, pull requests merged in 2020-07, with the labels that each got.

#417 Add Polish translations
  addons/ai/stringtable.xml
  addons/attributes/stringtable.xml
  addons/camera/stringtable.xml
  addons/common/stringtable.xml
  addons/compositions/stringtable.xml
  addons/context_actions/stringtable.xml
  addons/damage/stringtable.xml
  addons/editor/stringtable.xml
  addons/editor_previews/stringtable.xml
  addons/flashlight/stringtable.xml
  addons/garage/stringtable.xml
  addons/inventory/stringtable.xml
  addons/loadout/stringtable.xml
  addons/modules/stringtable.xml
  addons/placement/stringtable.xml
  addons/position_logics/stringtable.xml
Labels: translation

#424 Add display to configure pylon loadouts
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_hasPylons.sqf
  addons/pylons/$PBOPREFIX$
  addons/pylons/CfgEventHandlers.hpp
  addons/pylons/XEH_PREP.hpp
  addons/pylons/XEH_postInit.sqf
  addons/pylons/XEH_preInit.sqf
  addons/pylons/XEH_preStart.sqf
  addons/pylons/config.cpp
  addons/pylons/functions/fnc_configure.sqf
  addons/pylons/functions/fnc_handleConfirm.sqf
  addons/pylons/functions/fnc_handleMagazineSelect.sqf
  addons/pylons/functions/fnc_handleMirror.sqf
  addons/pylons/functions/fnc_handlePreset.sqf
  addons/pylons/functions/fnc_handleTurretButton.sqf
  addons/pylons/functions/script_component.hpp
  addons/pylons/gui.hpp
  addons/pylons/script_component.hpp
  addons/pylons/stringtable.xml
Labels: feature

#426 Fix Teleport Zeus context menu action when player is in a vehicle
  addons/context_actions/functions/fnc_teleportZeus.sqf
Labels: bug fix

#435 Prevent collisions when teleporting players using context menu
  addons/context_actions/functions/fnc_teleportPlayers.sqf
Labels: enhancement

#418 Improve loadout display positioning
  addons/loadout/gui.hpp
Labels: enhancement

#431 Fix VLS failing to strike target module
  addons/common/functions/fnc_fireVLS.sqf
Labels: bug fix

#419 Preload Addons
  addons/ai/config.cpp
  addons/area_markers/config.cpp
  addons/attributes/config.cpp
  addons/camera/config.cpp
  addons/common/config.cpp
  addons/compositions/config.cpp
  addons/context_actions/config.cpp
  addons/context_menu/config.cpp
  addons/custom_modules/config.cpp
  addons/damage/config.cpp
  addons/dialog/config.cpp
  addons/doors/config.cpp
  addons/editor/config.cpp
  addons/editor_previews/config.cpp
  addons/flashlight/config.cpp
  addons/garage/config.cpp
  addons/inventory/config.cpp
  addons/loadout/config.cpp
  addons/main/config.cpp
  addons/main/script_macros.hpp
  addons/markers_tree/config.cpp
  addons/modules/config.cpp
  addons/music/config.cpp
  addons/placement/config.cpp
  addons/position_logics/config.cpp
  addons/pylons/config.cpp
  addons/remote_control/config.cpp
  addons/visibility/config.cpp
  addons/vision/config.cpp
  extras/blank/config.cpp
  optionals/compat_ace/config.cpp
Labels: enhancement

#427 Overhaul Custom Objective module
  addons/tasks/$PBOPREFIX$
  addons/tasks/CfgEventHandlers.hpp
  addons/tasks/CfgTaskTypes.hpp
  addons/tasks/CfgVehicles.hpp
  addons/tasks/XEH_PREP.hpp
  addons/tasks/XEH_preInit.sqf
  addons/tasks/XEH_preStart.sqf
  addons/tasks/config.cpp
  addons/tasks/functions/fnc_init.sqf
  addons/tasks/functions/fnc_update.sqf
  addons/tasks/functions/script_component.hpp
  addons/tasks/gui.hpp
  addons/tasks/script_component.hpp
  addons/tasks/stringtable.xml
Labels: feature

#442 Fix context menu variables when hovering over a waypoint
  addons/context_menu/functions/fnc_openMenu.sqf
Labels: bug fix
