Repository zen-mod/ZEN, pull requests merged in 2020-11, with the labels that each got.

#55 Add HEMTT support
  .github/workflows/build.yml
  .github/workflows/translations.yml
  .gitignore
  Makefile
  azure-pipelines.yml
  hemtt.toml
  tools/config_style_checker.py
  tools/getArmake.ps1
  tools/get_hemtt.py
Labels: ignore changelog, tools

#483 Add waypoint loiter altitude attribute
  addons/attributes/initAttributes.sqf
Labels: feature

#477 Add option to select action type in Create Intel module
  addons/modules/functions/fnc_addIntelAction.sqf
  addons/modules/functions/fnc_moduleCreateIntel.sqf
  addons/modules/stringtable.xml
Labels: enhancement

#487 Remove Game Master module locality transfer fix timeout
  addons/modules/functions/fnc_bi_moduleCurator.sqf
Labels: cleanup
