Repository zen-mod/ZEN, pull requests merged in 2021-06, with the labels that each got.

#586 Add Show In Animation Viewer module
  addons/modules/CfgVehicles.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/config.cpp
  addons/modules/functions/fnc_moduleAnimationViewer.sqf
  addons/modules/stringtable.xml
  docs/user_guide/modules_list.md
Labels: feature

#584 Use hash map for markers tree cache
  addons/markers_tree/functions/fnc_compile.sqf
  addons/markers_tree/functions/fnc_populate.sqf
  addons/markers_tree/script_component.hpp
Labels: enhancement

#598 Cover Map - Fix IDC undef error
  addons/cover_map/functions/fnc_handleConfirm.sqf
  addons/cover_map/functions/fnc_handleDelete.sqf
  addons/cover_map/functions/fnc_handleDraw.sqf
  addons/cover_map/functions/fnc_handleLoad.sqf
  addons/cover_map/functions/fnc_handleMouseButtonUp.sqf
  addons/cover_map/functions/fnc_handleRotationChanged.sqf
  addons/cover_map/gui.hpp
  addons/cover_map/script_component.hpp
Labels: ignore changelog

#599 Cover Map - Fix missing semicolon
  addons/cover_map/gui.hpp
Labels: ignore changelog
