Repository zen-mod/ZEN, pull requests merged in 2021-01, with the labels that each got.

#509 Use version resolver for release drafter
  .github/release-drafter.yml
Labels: ignore changelog, tools

#508 Split notify job to different workflow
  .github/workflows/build.yml
  .github/workflows/notify.yml
Labels: ignore changelog, tools

#506 Add search building waypoint
  addons/ai/functions/fnc_waypointSearchBuilding.sqf
  addons/ai/stringtable.xml
  addons/attributes/CfgWaypointTypes.hpp
  addons/modules/CfgVehicles.hpp
  addons/modules/functions/fnc_moduleSearchBuilding.sqf
  addons/modules/stringtable.xml
Labels: feature

#505 Clean up compositions randomize button code
  addons/compositions/functions/fnc_buttonRandomize.sqf
  addons/compositions/functions/fnc_initDisplayCurator.sqf
Labels: cleanup

#492 Add Door State context menu action
  addons/doors/CfgContext.hpp
  addons/doors/CfgVehicles.hpp
  addons/doors/XEH_PREP.hpp
  addons/doors/config.cpp
  addons/doors/functions/fnc_configure.sqf
  addons/doors/functions/fnc_getActions.sqf
  addons/doors/functions/fnc_getState.sqf
  addons/doors/functions/fnc_setState.sqf
  addons/doors/functions/fnc_updatePFH.sqf
  addons/doors/script_component.hpp
  addons/doors/stringtable.xml
  docs/user_guide/context_actions.md
Labels: feature

#511 Several CI changes
  .github/workflows/notify.yml
  tools/stringtable_validator.py
  tools/stringtablediag.py
Labels: ignore changelog, tools

#504 Add Faction Filter
  addons/editor/functions/fnc_fixSideButtons.sqf
  addons/editor/functions/fnc_handleLoad.sqf
  addons/editor/functions/fnc_handleModeButtons.sqf
  addons/editor/functions/fnc_handleSideButtons.sqf
  addons/faction_filter/$PBOPREFIX$
  addons/faction_filter/CfgEventHandlers.hpp
  addons/faction_filter/XEH_postInit.sqf
  addons/faction_filter/XEH_preInit.sqf
  addons/faction_filter/XEH_preStart.sqf
  addons/faction_filter/config.cpp
  addons/faction_filter/script_component.hpp
  addons/faction_filter/stringtable.xml
Labels: feature

#514 Add Ampersand to core team
  AUTHORS.txt
Labels: ignore changelog

#512 Add HEMTT to build.py
  tools/build.py
Labels: ignore changelog, tools

#494 Fix custom modules not being added in ZGM missions
  addons/custom_modules/XEH_preInit.sqf
  addons/custom_modules/functions/fnc_addModules.sqf
  addons/editor/functions/fnc_handleLoad.sqf
Labels: bug fix

#518 Add Reset Loadout context menu action
  addons/context_actions/CfgContext.hpp
  docs/user_guide/context_actions.md
Labels: feature

#519 Use vectorDistance for doors max scan distance check
  addons/doors/functions/fnc_getActions.sqf
Labels: bug fix, ignore changelog

#521 Fix remote control owner variable not being reset after disconnect
  addons/remote_control/XEH_postInit.sqf
Labels: bug fix

#500 Add various improvements to the inventory display
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_getDefaultInventory.sqf
  addons/common/functions/fnc_initListNBoxSorting.sqf
  addons/common/functions/fnc_isWeapon.sqf
  addons/inventory/XEH_PREP.hpp
  addons/inventory/XEH_preInit.sqf
  addons/inventory/XEH_preStart.sqf
  addons/inventory/functions/fnc_clear.sqf
  addons/inventory/functions/fnc_configure.sqf
  addons/inventory/functions/fnc_getCargo.sqf
  addons/inventory/functions/fnc_getItemMass.sqf
  addons/inventory/functions/fnc_getWeaponItems.sqf
  addons/inventory/functions/fnc_keyDown.sqf
  addons/inventory/functions/fnc_modify.sqf
  addons/inventory/functions/fnc_preload.sqf
  addons/inventory/functions/fnc_refresh.sqf
  addons/inventory/functions/fnc_refreshList.sqf
  addons/inventory/functions/fnc_reset.sqf
  addons/inventory/functions/fnc_switchMode.sqf
  addons/inventory/functions/fnc_update.sqf
  addons/inventory/functions/fnc_updateButtons.sqf
  addons/inventory/functions/fnc_updateLoadBar.sqf
  addons/inventory/gui.hpp
  addons/inventory/script_component.hpp
  addons/inventory/stringtable.xml
Labels: enhancement

#522 Fix Game Master modules being deleted in multiplayer
  addons/modules/functions/fnc_bi_moduleCurator.sqf
Labels: bug fix

#393 CBRN hose support
  addons/common/functions/fnc_deserializeObjects.sqf
  addons/common/functions/fnc_exportMissionSQF.sqf
  addons/common/functions/fnc_openArsenal.sqf
Labels: feature

#499 Improve object serialization by saving vector dir and up
  addons/common/functions/fnc_deserializeObjects.sqf
  addons/common/functions/fnc_serializeObjects.sqf
Labels: bug fix

#532 Sort pylon magazine combo boxes alphabetically
  addons/pylons/functions/fnc_configure.sqf
Labels: enhancement
