Repository zen-mod/ZEN, pull requests merged in 2021-08, with the labels that each got.

#625 Restrict code execution to logged in admins
  addons/attributes/initAttributes.sqf
  addons/modules/functions/fnc_gui_executeCode.sqf
Labels: enhancement

#626 Update translations (mainly French and German)
  addons/ai/stringtable.xml
  addons/attributes/stringtable.xml
  addons/common/stringtable.xml
  addons/compositions/stringtable.xml
  addons/context_actions/stringtable.xml
  addons/context_menu/stringtable.xml
  addons/cover_map/stringtable.xml
  addons/doors/stringtable.xml
  addons/editor/stringtable.xml
  addons/flashlight/stringtable.xml
  addons/inventory/stringtable.xml
  addons/loadout/stringtable.xml
  addons/modules/stringtable.xml
  addons/pylons/functions/fnc_configure.sqf
  addons/pylons/stringtable.xml
  addons/remote_control/stringtable.xml
  addons/tasks/CfgTaskTypes.hpp
  addons/tasks/stringtable.xml
Labels: translation

#630 Update translations
  addons/ai/stringtable.xml
Labels: translation, ignore changelog

#627 Add Scale Object module
  addons/common/XEH_postInit.sqf
  addons/common/stringtable.xml
  addons/modules/CfgVehicles.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/config.cpp
  addons/modules/functions/fnc_moduleScaleObject.sqf
  addons/modules/script_component.hpp
  addons/modules/stringtable.xml
Labels: feature

#631 Tasks - Fix task type translations
  addons/tasks/CfgTaskTypes.hpp
  addons/tasks/stringtable.xml
Labels: translation, ignore changelog

#633 Add Chinese translation
  addons/ai/stringtable.xml
  addons/area_markers/stringtable.xml
  addons/attributes/stringtable.xml
  addons/camera/stringtable.xml
  addons/common/stringtable.xml
  addons/compositions/stringtable.xml
  addons/context_actions/stringtable.xml
  addons/context_menu/stringtable.xml
  addons/cover_map/stringtable.xml
  addons/custom_modules/stringtable.xml
  addons/damage/stringtable.xml
  addons/doors/stringtable.xml
  addons/editor/stringtable.xml
  addons/editor_previews/stringtable.xml
  addons/faction_filter/stringtable.xml
  addons/flashlight/stringtable.xml
  addons/garage/stringtable.xml
  addons/inventory/stringtable.xml
  addons/loadout/stringtable.xml
  addons/modules/stringtable.xml
  addons/placement/stringtable.xml
  addons/position_logics/stringtable.xml
  addons/pylons/stringtable.xml
  addons/remote_control/stringtable.xml
  addons/tasks/stringtable.xml
  addons/visibility/stringtable.xml
  addons/vision/stringtable.xml
Labels: translation

#634 Update contributors
  AUTHORS.txt
  tools/get_contributors.py
Labels: ignore changelog, tools

#635 Fix context menu not using modified action data
  addons/context_menu/functions/fnc_getActiveActions.sqf
Labels: bug fix
