Repository zen-mod/ZEN, pull requests merged in 2021-07, with the labels that each got.

#604 Improve Tracers module weapon compatibility
  addons/modules/functions/fnc_compileTracers.sqf
Labels: enhancement

#611 Editor - Improve group trees deselect path check
  addons/editor/functions/fnc_handleLoad.sqf
Labels: enhancement

#607 Improve plate number attribute condition
  addons/attributes/initAttributes.sqf
Labels: enhancement

#612 Remote Control - Add camera exit position setting
  addons/remote_control/CfgVehicles.hpp
  addons/remote_control/XEH_preInit.sqf
  addons/remote_control/functions/fnc_start.sqf
  addons/remote_control/initSettings.sqf
  addons/remote_control/script_component.hpp
  addons/remote_control/stringtable.xml
Labels: enhancement

#613 Remote Control - Add stopped event
  addons/remote_control/functions/fnc_start.sqf
  docs/frameworks/public_events.md
Labels: enhancement

#606 Add mod icons to Tracers module dialog lists
  addons/modules/functions/fnc_gui_tracers.sqf
  addons/modules/gui.hpp
Labels: enhancement

#616 Dialog - Fix issues when opened in 3DEN
  addons/dialog/functions/fnc_create.sqf
Labels: bug fix

#621 Fix comment style
  addons/editor/functions/fnc_bi_curatorObjectPlaced.sqf
Labels: ignore changelog

#614 Add Spanish translations
  addons/ai/stringtable.xml
Labels: translation

#618 Dialog - Fix multi-line edit box not displaying default text correctly
  addons/dialog/functions/fnc_gui_edit.sqf
Labels: bug fix

#602 Editor - Delete entire vehicle crew all at once
  addons/editor/functions/fnc_handleObjectPlaced.sqf
  addons/main/script_mod.hpp
Labels: enhancement

#623 Revert "Editor - Delete entire vehicle crew all at once"
  addons/editor/functions/fnc_handleObjectPlaced.sqf
  addons/main/script_mod.hpp
Labels: bug fix, ignore changelog
