Repository zen-mod/ZEN, pull requests merged in 2021-03, with the labels that each got.

#531 Improve pylon turret functionality by using getAllPylonsInfo
  addons/common/functions/fnc_exportMissionSQF.sqf
  addons/common/functions/fnc_getPylonTurret.sqf
  addons/pylons/functions/fnc_configure.sqf
  addons/pylons/functions/fnc_handleConfirm.sqf
  addons/pylons/functions/fnc_handleMagazineSelect.sqf
  addons/pylons/functions/fnc_handleTurretButton.sqf
Labels: 2.02, enhancement

#564 Upload build artifacts
  .github/workflows/build.yml
Labels: ignore changelog, tools

#515 Replace CBA hashes with base game hashes
  addons/common/functions/fnc_deserializeObjects.sqf
  addons/modules/functions/fnc_compileAircraft.sqf
  addons/modules/functions/fnc_compileReinforcements.sqf
  addons/modules/functions/fnc_gui_ambientFlyby.sqf
  addons/modules/functions/fnc_gui_spawnReinforcements.sqf
Labels: 2.02, optimization

#549 Add a Radius option for custom dialog sliders
  addons/dialog/functions/fnc_create.sqf
  addons/dialog/functions/fnc_gui_slider.sqf
  addons/dialog/script_component.hpp
  addons/modules/functions/fnc_moduleCreateIED.sqf
  addons/modules/functions/fnc_moduleEarthquake.sqf
  addons/modules/functions/fnc_moduleGarrison.sqf
  addons/modules/functions/fnc_moduleHideTerrainObjects.sqf
  addons/modules/functions/fnc_moduleLightSource.sqf
  addons/modules/functions/fnc_moduleNuke.sqf
  addons/modules/functions/fnc_modulePatrolArea.sqf
  addons/modules/functions/fnc_moduleSuicideBomber.sqf
  docs/frameworks/dynamic_dialog.md
Labels: feature

#481 Allow opening context menu by right clicking when AI are selected
  addons/context_menu/functions/fnc_initDisplayCurator.sqf
  addons/context_menu/initSettings.sqf
  addons/context_menu/stringtable.xml
  addons/editor/initKeybinds.sqf
Labels: enhancement

#574 Update Japanese translation
  addons/ai/stringtable.xml
  addons/attributes/stringtable.xml
  addons/common/stringtable.xml
  addons/compositions/stringtable.xml
  addons/context_actions/stringtable.xml
  addons/damage/stringtable.xml
  addons/doors/stringtable.xml
  addons/editor/stringtable.xml
  addons/editor_previews/stringtable.xml
  addons/faction_filter/stringtable.xml
  addons/flashlight/stringtable.xml
  addons/inventory/stringtable.xml
  addons/loadout/stringtable.xml
  addons/modules/stringtable.xml
  addons/music/stringtable.xml
  addons/placement/stringtable.xml
  addons/position_logics/stringtable.xml
  addons/pylons/stringtable.xml
  addons/tasks/stringtable.xml
  addons/vision/stringtable.xml
  extras/blank/stringtable.xml
  optionals/compat_ace/stringtable.xml
Labels: translation
