Repository zen-mod/ZEN, pull requests merged in 2021-02, with the labels that each got.

#538 Fix missing semicolon in gui.hpp for the inventory component
  addons/inventory/gui.hpp
Labels: bug fix, ignore changelog

#528 Add Unload Vehicle Cargo keybind and context menu action
  addons/context_actions/CfgContext.hpp
  addons/context_actions/XEH_PREP.hpp
  addons/context_actions/functions/fnc_canUnloadViV.sqf
  addons/context_actions/functions/fnc_unloadViV.sqf
  addons/editor/initKeybinds.sqf
  addons/editor/stringtable.xml
Labels: feature

#517 Add option to remove NVG when adding flashlights
  addons/modules/functions/fnc_moduleToggleFlashlights.sqf
  addons/modules/stringtable.xml
Labels: enhancement

#536 Add Hide Terrain Objects module
  addons/modules/CfgVehicles.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/config.cpp
  addons/modules/functions/fnc_moduleHideTerrainObjects.sqf
  addons/modules/functions/fnc_moduleHideZeus.sqf
  docs/user_guide/modules_list.md
Labels: feature

#535 Fix non-unique global event ID usage in Toggle Lamps module
  addons/modules/functions/fnc_moduleToggleLamps.sqf
Labels: bug fix

#516 Fix RC breaking when entering ACE arsenal
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_isRemoteControlled.sqf
  addons/common/functions/fnc_openArsenal.sqf
Labels: bug fix

#543 Fix incorrect variable name in openArsenal function
  addons/common/functions/fnc_openArsenal.sqf
Labels: bug fix, ignore changelog

#542 Reload Zeus Interface Keybind
  addons/editor/initKeybinds.sqf
  addons/editor/stringtable.xml
Labels: bug fix

#544 Misc cleanup for reload display keybind
  addons/editor/initKeybinds.sqf
  addons/editor/stringtable.xml
Labels: ignore changelog

#545 Fix variable in Flashlight Module
  addons/modules/functions/fnc_moduleToggleFlashlights.sqf
Labels: bug fix, ignore changelog

#548 Optimize Hide Terrain Objects module server events
  addons/modules/XEH_postInit.sqf
  addons/modules/functions/fnc_moduleHideTerrainObjects.sqf
Labels: ignore changelog, optimization

#547 Change Hide Terrain Objects module radius option to a slider
  addons/modules/functions/fnc_moduleHideTerrainObjects.sqf
Labels: enhancement, ignore changelog

#553 ACE Compat - Fix missing preStart XEH
  optionals/compat_ace/CfgEventHandlers.hpp
Labels: bug fix

#560 Fix remote vehicles not updating in garage
  addons/common/XEH_postInit.sqf
  addons/garage/functions/fnc_applyToAll.sqf
  addons/garage/functions/fnc_onAnimationSelect.sqf
  addons/garage/functions/fnc_onTextureSelect.sqf
Labels: bug fix

#510 Use isNotEqualTo
  addons/ai/functions/fnc_garrison.sqf
  addons/ai/functions/fnc_waypointFastrope.sqf
  addons/common/functions/fnc_collapseTree.sqf
  addons/common/functions/fnc_deserializeObjects.sqf
  addons/common/functions/fnc_exportMissionSQF.sqf
  addons/common/functions/fnc_getDLC.sqf
  addons/compositions/functions/fnc_initDisplayCurator.sqf
  addons/context_actions/functions/fnc_canUnloadViV.sqf
  addons/context_actions/functions/fnc_unloadViV.sqf
  addons/context_menu/functions/fnc_createContextGroup.sqf
  addons/context_menu/functions/fnc_getActiveActions.sqf
  addons/editor/functions/fnc_handleLoad.sqf
  addons/editor/initKeybinds.sqf
  addons/garage/functions/fnc_handleMouse.sqf
  addons/loadout/XEH_preInit.sqf
  addons/main/script_mod.hpp
  addons/modules/functions/fnc_addIntelAction.sqf
  addons/modules/functions/fnc_compileCAS.sqf
  addons/modules/functions/fnc_moduleCAS.sqf
  addons/modules/functions/fnc_moduleToggleLamps.sqf
  addons/position_logics/functions/fnc_exists.sqf
  addons/pylons/functions/fnc_handleConfirm.sqf
  addons/remote_control/functions/fnc_start.sqf
  addons/tasks/functions/fnc_update.sqf
  addons/visibility/functions/fnc_draw.sqf
  tools/sqf_validator.py
Labels: 2.02, optimization
