Repository zen-mod/ZEN, pull requests merged in 2022-12, with the labels that each got.

#686 Visibility - Add during placement only mode and max distance setting
  addons/common/functions/fnc_getPosFromScreen.sqf
  addons/common/functions/fnc_selectPosition.sqf
  addons/context_menu/script_component.hpp
  addons/visibility/XEH_postInit.sqf
  addons/visibility/functions/fnc_draw.sqf
  addons/visibility/initSettings.sqf
  addons/visibility/script_component.hpp
  addons/visibility/stringtable.xml
Labels: enhancement

#689 Add placement preview support to recent tree
  addons/placement/XEH_postInit.sqf
  addons/placement/functions/fnc_handleTreeChange.sqf
Labels: enhancement

#684 Add mod icons to create unit trees
  addons/editor/XEH_PREP.hpp
  addons/editor/functions/fnc_addModIcons.sqf
  addons/editor/functions/fnc_handleLoad.sqf
  addons/editor/initSettings.sqf
  addons/editor/stringtable.xml
Labels: feature

#690 Improve placement preview mouse position handling
  addons/editor/XEH_preInit.sqf
  addons/editor/functions/fnc_handleLoad.sqf
  addons/placement/functions/fnc_updatePreview.sqf
Labels: enhancement

#694 Ignore .vscode folder
  .gitignore
Labels: ignore changelog

#691 Add attach/detach keybinds and allow editing attached objects directly
  addons/attached_objects/$PBOPREFIX$
  addons/attached_objects/CfgEventHandlers.hpp
  addons/attached_objects/CfgVehicles.hpp
  addons/attached_objects/XEH_PREP.hpp
  addons/attached_objects/XEH_preInit.sqf
  addons/attached_objects/XEH_preStart.sqf
  addons/attached_objects/config.cpp
  addons/attached_objects/functions/fnc_attach.sqf
  addons/attached_objects/functions/fnc_detach.sqf
  addons/attached_objects/functions/fnc_handleObjectEdited.sqf
  addons/attached_objects/functions/fnc_module.sqf
  addons/attached_objects/functions/script_component.hpp
  addons/attached_objects/initKeybinds.sqf
  addons/attached_objects/script_component.hpp
  addons/attached_objects/stringtable.xml
  addons/editor/functions/fnc_bi_curatorObjectEdited.sqf
  addons/modules/CfgVehicles.hpp
  addons/modules/XEH_PREP.hpp
  addons/modules/config.cpp
  addons/modules/functions/fnc_moduleAttachTo.sqf
  addons/modules/stringtable.xml
Labels: feature

#693 Improve positioning of Teleport Players module
  addons/modules/functions/fnc_moduleTeleportPlayers.sqf
  addons/modules/script_component.hpp
Labels: enhancement

#697 Inventory - Disable for CAManBase objects
  addons/context_actions/functions/fnc_canEditInventory.sqf
  addons/inventory/XEH_preInit.sqf
Labels: bug fix

#698 Mark created groups for autodeletion
  addons/editor/functions/fnc_handleObjectPlaced.sqf
Labels: enhancement
