Repository zen-mod/ZEN, pull requests merged in 2023-10, with the labels that each got.

#745 Misc - Update logos
  README.md
  extras/assets/logo/black/ZEN-Logo.jpg
  extras/assets/logo/black/ZEN-Logo.png
  extras/assets/logo/logo_zen_black.png
  extras/assets/logo/white/ZEN-Logo.jpg
  extras/assets/logo/white/ZEN-Logo.png
  extras/assets/logo/workshop/logo_zen_ca.png
  extras/assets/logo/workshop/logo_zen_small_ca.png
Labels: ignore changelog, documentation

#746 Context Menu - Use setCuratorSelected
  addons/context_menu/functions/fnc_initDisplayCurator.sqf
  addons/main/script_mod.hpp
Labels: enhancement, 2.14

#748 Fix Hide Terrain Objects module for tall objects
  addons/modules/XEH_postInit.sqf
Labels: enhancement
