Repository zen-mod/ZEN, pull requests merged in 2023-05, with the labels that each got.

#734 Fix typo for garrisoned flag
  addons/ai/functions/fnc_unGarrison.sqf
Labels: bug fix

#729 Add Ping Zeus keybind
  addons/editor/XEH_PREP.hpp
  addons/editor/XEH_postInit.sqf
  addons/editor/XEH_preInit.sqf
  addons/editor/functions/fnc_handleCuratorPinged.sqf
  addons/editor/functions/fnc_handleKeyDown.sqf
  addons/editor/functions/fnc_handleKeyUp.sqf
  addons/editor/functions/fnc_handleLoad.sqf
  addons/editor/functions/fnc_pingCurators.sqf
  addons/editor/initKeybinds.sqf
  addons/editor/stringtable.xml
Labels: feature

#724 Add custom tree for placing area markers
  addons/area_markers/CfgContext.hpp
  addons/area_markers/CfgVehicles.hpp
  addons/area_markers/XEH_PREP.hpp
  addons/area_markers/config.cpp
  addons/area_markers/functions/fnc_createMarker.sqf
  addons/area_markers/functions/fnc_module.sqf
  addons/area_markers/gui.hpp
  addons/area_markers/script_component.hpp
  addons/area_markers/stringtable.xml
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_execAfterNFrames.sqf
  addons/editor/RscDisplayCurator.hpp
  addons/editor/XEH_PREP.hpp
  addons/editor/XEH_postInit.sqf
  addons/editor/functions/fnc_fixSideButtons.sqf
  addons/editor/functions/fnc_handleLoad.sqf
  addons/editor/functions/fnc_handleTreeButtons.sqf
  addons/markers_tree/RscDisplayCurator.hpp
  addons/markers_tree/XEH_PREP.hpp
  addons/markers_tree/XEH_postInit.sqf
  addons/markers_tree/XEH_preInit.sqf
  addons/markers_tree/config.cpp
  addons/markers_tree/functions/fnc_compile.sqf
  addons/markers_tree/functions/fnc_handleAreasSelect.sqf
  addons/markers_tree/functions/fnc_handleDraw.sqf
  addons/markers_tree/functions/fnc_handleEngineSelect.sqf
  addons/markers_tree/functions/fnc_handleIconsSelect.sqf
  addons/markers_tree/functions/fnc_handleModeChange.sqf
  addons/markers_tree/functions/fnc_handleMouseButtonDown.sqf
  addons/markers_tree/functions/fnc_handleMouseButtonUp.sqf
  addons/markers_tree/functions/fnc_handleMouseMoving.sqf
  addons/markers_tree/functions/fnc_handleSubModeClicked.sqf
  addons/markers_tree/functions/fnc_handleTreeButtons.sqf
  addons/markers_tree/functions/fnc_handleTreeChange.sqf
  addons/markers_tree/functions/fnc_initDisplayCurator.sqf
  addons/markers_tree/functions/fnc_populate.sqf
  addons/markers_tree/script_component.hpp
Labels: feature

#736 Area Markers - Add Editable Markers setting
  addons/area_markers/XEH_postInit.sqf
  addons/area_markers/XEH_preInit.sqf
  addons/area_markers/functions/fnc_deleteIcon.sqf
  addons/area_markers/functions/fnc_isEditable.sqf
  addons/area_markers/initSettings.sqf
  addons/area_markers/script_component.hpp
  addons/area_markers/stringtable.xml
Labels: enhancement

#716 Add settings to toggle attributes
  addons/attributes/XEH_preInit.sqf
  addons/attributes/initAttributes.sqf
  addons/attributes/initSettings.sqf
  addons/attributes/stringtable.xml
  addons/damage/XEH_preInit.sqf
  addons/damage/initSettings.sqf
  addons/garage/XEH_preInit.sqf
  addons/garage/initSettings.sqf
  addons/inventory/XEH_preInit.sqf
  addons/inventory/initSettings.sqf
Labels: enhancement

#737 Use profile name for Ping Zeus keybind
  addons/editor/functions/fnc_pingCurators.sqf
  addons/editor/initKeybinds.sqf
Labels: bug fix
