Repository zen-mod/ZEN, pull requests merged in 2023-11, with the labels that each got.

#747 Common - Use CBA_fnc_execAfterNFrames
  addons/common/XEH_PREP.hpp
  addons/common/functions/fnc_execAfterNFrames.sqf
  addons/main/script_mod.hpp
  addons/markers_tree/functions/fnc_initDisplayCurator.sqf
Labels: enhancement

#743 Conditionally Load Compats
  addons/compat_ace/$PBOPREFIX$
  addons/compat_ace/ACE_ZeusActions.hpp
  addons/compat_ace/CfgEventHandlers.hpp
  addons/compat_ace/CfgVehicles.hpp
  addons/compat_ace/CfgWaypointTypes.hpp
  addons/compat_ace/XEH_PREP.hpp
  addons/compat_ace/XEH_preInit.sqf
  addons/compat_ace/XEH_preStart.sqf
  addons/compat_ace/config.cpp
  addons/compat_ace/functions/fnc_canFastrope.sqf
  addons/compat_ace/functions/fnc_canRemoteControl.sqf
  addons/compat_ace/functions/fnc_remoteControl.sqf
  addons/compat_ace/functions/fnc_waypointFastrope.sqf
  addons/compat_ace/functions/script_component.hpp
  addons/compat_ace/initSettings.sqf
  addons/compat_ace/script_component.hpp
  addons/compat_ace/stringtable.xml
  addons/compat_advanced_rappelling/$PBOPREFIX$
  addons/compat_advanced_rappelling/CfgEventHandlers.hpp
  addons/compat_advanced_rappelling/CfgWaypointTypes.hpp
  addons/compat_advanced_rappelling/XEH_PREP.hpp
  addons/compat_advanced_rappelling/XEH_preInit.sqf
  addons/compat_advanced_rappelling/XEH_preStart.sqf
  addons/compat_advanced_rappelling/config.cpp
  addons/compat_advanced_rappelling/functions/fnc_canRappel.sqf
  addons/compat_advanced_rappelling/functions/fnc_waypointRappel.sqf
  addons/compat_advanced_rappelling/functions/script_component.hpp
  addons/compat_advanced_rappelling/script_component.hpp
  addons/compat_advanced_rappelling/stringtable.xml
Labels: enhancement, 2.14

#753 Add Supply Cargo Attributes
  addons/attributes/initAttributes.sqf
  addons/attributes/initSettings.sqf
  addons/attributes/stringtable.xml
  addons/common/XEH_postInit.sqf
Labels: feature
