Repository zen-mod/ZEN, pull requests merged in 2023-03, with the labels that each got.

#707 Fix select position ignoring overlapping controls
  addons/common/XEH_PREP.hpp
  addons/common/XEH_preInit.sqf
  addons/common/functions/fnc_displayCuratorLoad.sqf
  addons/common/functions/fnc_isCursorOnMouseArea.sqf
  addons/common/functions/fnc_selectPosition.sqf
  addons/editor/XEH_preInit.sqf
  addons/editor/functions/fnc_handleLoad.sqf
  addons/main/script_mod.hpp
  addons/placement/functions/fnc_updatePreview.sqf
Labels: bug fix, 2.12

#496 AI Control Keybinds
  addons/ai/functions/fnc_suppressiveFire.sqf
  addons/common/XEH_PREP.hpp
  addons/common/XEH_postInit.sqf
  addons/common/functions/fnc_canFire.sqf
  addons/common/functions/fnc_drawHint.sqf
  addons/common/functions/fnc_fireWeapon.sqf
  addons/common/functions/fnc_forceFire.sqf
  addons/common/functions/fnc_getAllTurrets.sqf
  addons/common/functions/fnc_getEffectiveGunner.sqf
  addons/common/functions/fnc_isReloading.sqf
  addons/common/functions/fnc_isUnitFFV.sqf
  addons/editor/initKeybinds.sqf
  addons/editor/stringtable.xml
Labels: feature

#537 Add Switch Weapon context menu actions for vehicles
  addons/common/XEH_PREP.hpp
  addons/common/XEH_postInit.sqf
  addons/common/functions/fnc_getGunnerName.sqf
  addons/common/functions/fnc_loadMagazineInstantly.sqf
  addons/context_actions/CfgContext.hpp
  addons/context_actions/XEH_PREP.hpp
  addons/context_actions/functions/fnc_getVehicleWeaponActions.sqf
  addons/context_actions/functions/fnc_switchVehicleWeapon.sqf
  addons/loadout/functions/fnc_getWeaponName.sqf
Labels: feature

#704 Add Building Markers
  addons/attributes/initAttributes.sqf
  addons/building_markers/$PBOPREFIX$
  addons/building_markers/CfgEventHandlers.hpp
  addons/building_markers/XEH_PREP.hpp
  addons/building_markers/XEH_postInit.sqf
  addons/building_markers/XEH_preInit.sqf
  addons/building_markers/XEH_preStart.sqf
  addons/building_markers/config.cpp
  addons/building_markers/functions/fnc_handleObjectEdited.sqf
  addons/building_markers/functions/fnc_handleObjectPlaced.sqf
  addons/building_markers/functions/fnc_set.sqf
  addons/building_markers/functions/script_component.hpp
  addons/building_markers/initSettings.sqf
  addons/building_markers/script_component.hpp
  addons/building_markers/stringtable.xml
  addons/placement/functions/fnc_handleObjectPlaced.sqf
  docs/user_guide/attributes.md
Labels: feature

#710 Fix width adjustment for context menu mouse area controls
  addons/context_menu/functions/fnc_createContextGroup.sqf
Labels: bug fix

#711 Add Toggle Object Editability keybind
  addons/common/XEH_PREP.hpp
  addons/common/XEH_postInit.sqf
  addons/common/functions/fnc_deserializeObjects.sqf
  addons/common/functions/fnc_updateEditableObjects.sqf
  addons/context_actions/functions/fnc_openEditableObjectsDialog.sqf
  addons/context_actions/functions/fnc_updateEditableObjects.sqf
  addons/editor/initKeybinds.sqf
  addons/editor/stringtable.xml
  addons/modules/functions/fnc_moduleAmbientFlyby.sqf
  addons/modules/functions/fnc_moduleCreateIntel.sqf
  addons/modules/functions/fnc_moduleCreateMinefield.sqf
  addons/modules/functions/fnc_moduleCreateTeleporterServer.sqf
  addons/modules/functions/fnc_moduleEditableObjects.sqf
  addons/modules/functions/fnc_moduleEffectFireLocal.sqf
  addons/modules/functions/fnc_moduleLightSource.sqf
  addons/modules/functions/fnc_moduleSitOnChair.sqf
  addons/modules/functions/fnc_moduleSpawnCarrier.sqf
  addons/modules/functions/fnc_moduleSpawnDestroyer.sqf
  addons/modules/functions/fnc_moduleSpawnReinforcements.sqf
  addons/position_logics/functions/fnc_add.sqf
Labels: feature

#713 Fix attached object rotation
  addons/attached_objects/functions/fnc_handleObjectEdited.sqf
Labels: bug fix, ignore changelog

#714 Fix Suppressive Fire module fire mode string
  addons/modules/functions/fnc_moduleSuppressiveFire.sqf
Labels: bug fix, ignore changelog

#712 Fix laser cycling too quickly
  addons/common/functions/fnc_canFire.sqf
  addons/common/functions/fnc_fireWeapon.sqf
Labels: bug fix, ignore changelog

#715 Area Markers - Fix module and context menu action
  addons/area_markers/CfgContext.hpp
  addons/area_markers/functions/fnc_module.sqf
Labels: bug fix, ignore changelog

#720 Improve Watch Cursor and Watch Curator Camera keybinds
  addons/common/XEH_PREP.hpp
  addons/common/XEH_postInit.sqf
  addons/common/functions/fnc_forceWatch.sqf
  addons/editor/initKeybinds.sqf
Labels: enhancement

#721 Add Toggle Laser keybind
  addons/common/XEH_PREP.hpp
  addons/common/XEH_postInit.sqf
  addons/common/functions/fnc_setVehicleLaserState.sqf
  addons/editor/initKeybinds.sqf
  addons/editor/stringtable.xml
Labels: feature

#723 Improve conditions for Engine and Lights attributes
  addons/attributes/initAttributes.sqf
Labels: enhancement

#722 Add support for waypoint type conditions and priority
  addons/attributes/CfgWaypointTypes.hpp
  addons/attributes/functions/fnc_compileWaypoints.sqf
  addons/attributes/functions/fnc_gui_waypoint.sqf
  addons/attributes/gui.hpp
  docs/frameworks/custom_waypoints.md
Labels: enhancement

#726 Add icon for Scale Object module
  addons/modules/CfgVehicles.hpp
Labels: enhancement
