Repository zen-mod/ZEN, pull requests merged in 2024-05, with the labels that each got.

#761 Update Japanese translation
  addons/area_markers/stringtable.xml
  addons/attached_objects/stringtable.xml
  addons/attributes/stringtable.xml
  addons/building_markers/stringtable.xml
  addons/camera/stringtable.xml
  addons/common/stringtable.xml
  addons/compat_advanced_rappelling/stringtable.xml
  addons/context_actions/stringtable.xml
  addons/cover_map/stringtable.xml
  addons/editor/stringtable.xml
  addons/modules/stringtable.xml
  addons/remote_control/stringtable.xml
  addons/visibility/stringtable.xml
Labels: translation

#763 Modules - Fix Change Side module
  addons/common/functions/fnc_changeGroupSide.sqf
Labels: bug fix

#764 Common - Optimise marker global broadcast for exporting SQF
  addons/common/functions/fnc_exportMissionSQF.sqf
Labels: optimization
