Repository zen-mod/ZEN, pull requests merged in 2025-01, with the labels that each got.

#792 General - Fix and apply HEMTT suggestions
  .hemtt/lints.toml
  addons/ai/functions/fnc_canThrowGrenade.sqf
  addons/ai/functions/fnc_garrison.sqf
  addons/ai/functions/fnc_searchBuilding.sqf
  addons/area_markers/functions/fnc_applyProperties.sqf
  addons/area_markers/functions/fnc_createMarker.sqf
  addons/common/functions/fnc_displayCuratorLoad.sqf
  addons/common/functions/fnc_serializeObjects.sqf
  addons/common/gui.hpp
  addons/context_actions/functions/fnc_teleportZeus.sqf
  addons/cover_map/functions/fnc_create.sqf
  addons/editor/initKeybinds.inc.sqf
  addons/modules/functions/fnc_moduleTeleportPlayers.sqf
Labels: ignore changelog, cleanup, tools

#790 Docs - Fix ACE3 webpage links
  README.md
  docs/development/coding_guidelines.md
  docs/home.md
  tools/deploy.py
Labels: ignore changelog, documentation

#786 Fix Attach Flag module not supporting all flag pole types
  addons/modules/functions/fnc_moduleAttachFlag.sqf
Labels: bug fix

#787 Add French translations
  addons/ai/stringtable.xml
  addons/area_markers/stringtable.xml
  addons/attached_objects/stringtable.xml
  addons/attributes/stringtable.xml
  addons/building_markers/stringtable.xml
  addons/common/stringtable.xml
  addons/compat_ace/stringtable.xml
  addons/compat_advanced_rappelling/stringtable.xml
  addons/context_actions/stringtable.xml
  addons/context_menu/stringtable.xml
  addons/cover_map/stringtable.xml
  addons/damage/stringtable.xml
  addons/editor/stringtable.xml
  addons/editor_previews/stringtable.xml
  addons/flashlight/stringtable.xml
  addons/garage/stringtable.xml
  addons/inventory/stringtable.xml
  addons/loadout/stringtable.xml
  addons/modules/stringtable.xml
  addons/placement/stringtable.xml
  addons/position_logics/stringtable.xml
  addons/pylons/stringtable.xml
  addons/remote_control/stringtable.xml
  addons/tasks/stringtable.xml
  addons/visibility/stringtable.xml
  extras/blank/stringtable.xml
Labels: translation
